### ISSUE TITLE
Multi-root VS Code workspace

### ISSUE THREAD

**Issue by jpokrzyk** [firsttris/vscode-jest-runner#1]
This doesn't seem to work in a multi-root VS Code workspace.

```bash
node --inspect-brk ${workspaceRoot}/node_modules/.bin/jest -i "-t sendMessageTest"
➜  functions git:(task-notifications) ✗ node --inspect-brk ${workspaceRoot}/node_modules/.bin/jest -i "-t sendMessageTest"
Debugger listening on ws://127.0.0.1:9229/a8018417-3540-46de-b81e-25c8a7090175
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
module.js:538
    throw err;
    ^

Error: Cannot find module '/node_modules/.bin/jest'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by firsttris** [comment]
an easy way to resolve this would be: 

i could check if the addon finds jest in the workspace e.g. '/node_modules/.bin/jest' if not use the global jest version.

of course this would require a globally installed jest version.

what do you think ?

best regards 
Tristan

**Comment by jpokrzyk** [comment]
Yea that would definitely work. Before you do anything I'll dig around a little.

`workspaceRoot` has been deprecated for `workspaceRootFolder`. But I think it's still going to yield the same results. There's got to be an API to get the workspace project name and then do a ${workspaceRootFolder:project} as a compound per https://code.visualstudio.com/docs/editor/multi-root-workspaces

That's just me quickly looking at this though.

**Comment by firsttris** [comment]
hey sir,

i have found out i should now use ${workspaceFolder}

furthermore i added a ***jestPath*** config varialbe where you can define the absolut path to jest.

because if you ran ***run Jest*** im running jest from terminal and can't even use this vscode variables e.g ${workspaceFolder}

can you check how this works out for vscode workspaces ?

**Comment by jpokrzyk** [comment]
Sweet. Yea the `jestPath` worked well.

But I'm still getting an error with the default config. Definitely looks like it should be working.
```
➜  functions git:(task-notifications) ✗ node --inspect-brk=17060 --inspect-brk ${workspaceFolder}/node_modules/.bin/jest -i -t sendMessageTest
Debugger listening on ws://127.0.0.1:17060/5a5d99b0-5210-4695-bfca-719489b5a37d
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
module.js:538
    throw err;
    ^

Error: Cannot find module '/node_modules/.bin/jest'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```
`${workspaceFolder}/node_modules/.bin/jest` seems correct per https://code.visualstudio.com/docs/editor/variables-reference#_variables-scoped-per-workspace-folder

### Debugging
I'd debug this myself, but getting set up to debug an extension seems like more time than I have today or tomorrow. Multi-root workspaces are super easy to create if you have tried it. 

![image](https://user-images.githubusercontent.com/4333958/36274528-fbe0e7c6-1255-11e8-8dc8-4ec98b9fd08f.png)

But I certainly don't mind helping out. If you assign this over to me I might have some time this weekend.

**Comment by jpokrzyk** [comment]
Great extension by the way. `vscode-jest` is also great, but it was a little too obtrusive for me. Got annoyed with it after a few minutes.

**Comment by firsttris** [comment]
changed it again to always to the first workspace folder
https://github.com/firsttris/vscode-jest-runner/blob/master/src/extension.ts#L21
(for run & debug)
let me know how this works
