### ISSUE TITLE
Skipped tests don't run in the debugger

### ISSUE THREAD

**Issue by feederaccount** [firsttris/vscode-jest-runner#102]
I have a feeling this is a wider issue with Jest but I am curious if this plugin could solve it.

When doing TDD there are often unit tests that are a work in progress or, for whatever reason, we do not want to run as part of our wider package of tests. Jest gives us the `test.skip()` and `describe.skip()` functions as an alternative to commenting out these blocks of code.

The VSCode Jest Runner is great at making it easy to run and debug single tests, but whenever we have one of these such tests and we click `Debug` Jest passes over it and no breakpoints are hit.

![image](https://user-images.githubusercontent.com/67879604/92487867-b84bc680-f1e5-11ea-8faa-3b0a4eacb967.png)

Is there a way to debug a test without having it run when an `npm test` is performed?

**Comment by firsttris** [comment]
hey @feederaccount 

unfortunately, not that i know of.

**Comment by feederaccount** [comment]
@firsttris Oh well, maybe something for me to submit to the Jest repo instead.

I'll close this now then.
