### ISSUE TITLE
Run | Debug CodeLens links disappear for each block

### ISSUE THREAD

**Issue by dcrystalj** [firsttris/vscode-jest-runner#107]
When having parametrized test in format:

```
it.each([...])('test name', () => {})
```

run | debug is not displayed

**Comment by firsttris** [comment]
thx for reporting @dcrystalj 

there is already a corresponding issue https://github.com/firsttris/vscode-jest-runner/issues/55

but i leave yours open as well since its about the CodeLens

**Comment by firsttris** [comment]
fixed now
