### ISSUE TITLE
Run | Debug disappears when optional chaining operator is encountered (parsing fails)

### ISSUE THREAD

**Issue by JonathanWilbur** [firsttris/vscode-jest-runner#108]
I am almost certain this is a bug with the [Jest Editor Support](https://github.com/jest-community/jest-editor-support) library, but I am just letting you know, because it critically affects this extension.

See [this issue](https://github.com/jest-community/jest-editor-support/issues/51) for more information.

**Comment by firsttris** [comment]
thx for reporting @JonathanWilbur

**Comment by firsttris** [comment]
should be fixed with v0.4.38 if not please re-open
