### ISSUE TITLE
Setting up jestrunner.jestPath option also for folder.

### ISSUE THREAD

**Issue by floratmin** [firsttris/vscode-jest-runner#112]
I am setting up schematic for nx to create a svelte application with tests. So I am setting the option `jestrunner.jestPath` to point to the jest executable in the `node_modules` folder in the file `.vscode/settings.json`. This option is only available in a per user or per workspace setting. When the nx workspace is created as a folder in a vscode workspace, then this folder setting is ignored in a folder level. Therefore I have to set this setting in the vscode workspace settings. It would be nice for the user experience, if this setting would also be recognized as a folder setting, which I can generate automatically with nx schematics.

**Comment by firsttris** [comment]
Hey @floratmin 

not really understanding what u are trying to achieve, could explain it in more detail? or maybe post a picture of your repo?

vscode-jest-runner should detect jest bin / folder automatically based on the jest.config.js location.

**Comment by firsttris** [comment]
@floratmin could you check 0.4.29 there was a bug in 0.4.28 which could have caused your issue?

**Comment by firsttris** [comment]
with the newest version jest runner automatically pics the nearest jest binary from the hierarchy which may also fix your issue,
please re-open a new issue, if you still have problems.
