### ISSUE TITLE
Upgrading to 0.4.28 breaks debugging?

### ISSUE THREAD

**Issue by m-arran** [firsttris/vscode-jest-runner#113]
![image](https://user-images.githubusercontent.com/61283978/97162518-3c96e080-1777-11eb-92c9-1478d45b821d.png)

Downgrading to 0.4.27 and it works fine again.

Any ideas?

**Comment by firsttris** [comment]
hey  @m-arran sorry that we broke it with 0.4.28

@jenspalmqvist is it working for you?

**Comment by firsttris** [comment]
hey @m-arran i reverted the commit, could you check if 0.4.29 is working again?

**Comment by m-arran** [comment]
Hi @firsttris I have just updated to 0.4.29 and it works. Thank you for this.
