### ISSUE TITLE
Tests not found when test path contains `[` or `]`

### ISSUE THREAD

**Issue by MGough** [firsttris/vscode-jest-runner#114]
This might be an issue with my configuration, but I've not been able to work out if there's a way to resolve it.

Our codebase has square brackets in directory and filenames, for example `pages/api/[username].test.js`, or `pages/api/[username]/someEndpoint.test.js`.

When VSCode-jest-runner builds the command it doesn't escape the square brackets in the file path. It does escape them in the `-t` section. Subsequently the tests are not found.

The reason for having `[]` characters in the path is due to them having a special purpose in Next.js, they are necessary in the path, so removing them is not a possible solution.

**Comment by firsttris** [comment]
your right, i don't think we escape that path

**Comment by thiagobbt** [comment]
Just to add on this, paths containing a plus sign (+) also makes the test not to be found, making me think the path is parsed as a regex by jest

**Comment by firsttris** [comment]
we have a function which takes care of all the regex escaping but i think it will only be applied for the testname not the path
https://github.com/firsttris/vscode-jest-runner/blob/master/src/util.ts#L9

this should be applied to the path as well.

**Comment by WolfspiritM** [comment]
We're also having that issue and are not able to run ngrx tests as they contain a "+" in the path.

**Comment by firsttris** [comment]
should be fixed with v0.4.35
