### ISSUE TITLE
0.4.28 breaks monorepo support (NX)

### ISSUE THREAD

**Issue by samcoenen** [firsttris/vscode-jest-runner#115]
This plugin was working fine inside an NX monorepo until 0.4.27, but the 0.4.28 update broke it.

When running a test with the 0.4.27, the output is:

```
cd '/path/to/my/workspace'
node '/path/to/my/workspace/%                             
node '/path/to/my/workspace/node_modules/.bin/jest' '/path/to/my/workspace/libs/shared/ui/form/src/lib/components/inputs/input-code/input-code.component.spec.ts' -c '/path/to/my/workspace/libs/shared/ui/form/jest.config.js' -t 'InputCodeComponent'
```

With version 0.4.28:

```
cd '/path/to/my/workspace'                             
cd '/path/to/my/workspace/libs/shared/ui/form'
node '/path/to/my/workspace/libs/shared/ui/form/node_modules/.bin/jest' '/path/to/my/workspace/libs/shared/ui/form/src/lib/components/inputs/input-code/input-code.component.spec.ts' -c '/path/to/my/worspace/libs/shared/ui/form/jest.config.js' -t 'InputCodeComponent'
```

It's trying to load Jest from a `node_modules` folder inside my library, which doesn't exist causing it to crash.

Updating the projectPath inside the config for this plugin to "." fixes the problem, but that's not documented anywhere:

```
"jestrunner.projectPath": "."
```

With an empty projectPath (default), it crashes.

**Comment by firsttris** [comment]
so you have a jest.config.js in the package but the jest dependency only in the root directory. correct?

our idea was that the jest config would be in the same package then the dependency. @jenspalmqvist  @vrptnc 

if you add jest to your package dev dependecy in '/path/to/my/workspace/libs/shared/ui/form'
it should create a jest bin in '/path/to/my/workspace/libs/shared/ui/formnode_modules/.bin/jest'

will it then work?

we will fix this asap.

**Comment by samcoenen** [comment]
> so you have a jest.config.js in the package but the jest dependency only in the root directory. correct?
That is correct.

Our project only has 1 package.json and node_modules folder (in the root folder). We have hundreds of libraries in this monorepo, if they'd all require their own unique node_modules, it'd be a disaster to keep in sync with each other and would waste a lot of storage.

We have a jest.config.js in the root but also in the separate library providing custom config for that specific library. Example:

```
module.exports = {
  preset: '../../../../jest.preset.js',
  coverageDirectory: '../../../../coverage/libs/shared/ui/form',
  setupFilesAfterEnv: ['../../../../test-setup.ts'],
  displayName: 'shared-ui-form',
};
```

Manually copy'ing Jest inside a fake node_module folder in our small libraries works fine, but we'd have to do this for hundreds of libraries which is not really feasible. 🙂

**Comment by firsttris** [comment]
hey @samcoenen i reverted the commit, could you check if 0.4.29 is working again?

**Comment by samcoenen** [comment]
0.4.29 has indeed fixed the issue for us. 👍
