### ISSUE TITLE
Allow to override inspect flag for debug command (VSCode 1.50.1)

### ISSUE THREAD

**Issue by PizzaPartyInc** [firsttris/vscode-jest-runner#118]
Hi!

### Intro
With recent VSCode update  - the "Auto Attach" options were changed and with it debugging commands with auto attaching should be adjusted as well. See more info in links below:

- https://github.com/microsoft/vscode/issues/108925
- https://github.com/microsoft/vscode-js-debug/blob/master/COMMON_PROBLEMS.md#my-app-doesnt-start-run-and-i-use---inspect-brk-to-load-it

### Problem
With Jest Runner, the command for debug still works, but there is 1 case where it stops behaving as before.
If I right-click on some test and choose "Debug Jest" - a command like this will be generated:

```bash
cd 'e:\Projects\ProjectNamespace\Project'; & 'C:\Program Files\nodejs\node.exe' '--inspect-brk=41073' 'node_modules\jest\bin\jest.js' 'e:/Projects/ProjectNamespace/Project/services/serviceName/src/path-to-test-file.spec.ts' '-c' 'e:/Projects/ProjectNamespace/Project/services/serviceName/jest.config.js' '-t' 'test identifier' '--runInBand'
```

This works. But, if after it's execution I click "Arrow Up" button in the terminal to bring out the last executed command (same as before) and run it directly from same terminal window - the Debugger will not be attached and terminal will just wait on lines:
```
Debugger listening on ws://127.0.0.1:10834/c0ebe329-608d-484d-b260-bb532e65faf1
For help, see: https://nodejs.org/en/docs/inspector
```
I managed to make this scenario work by replacing `--inspect-brk=41073` with `--inspect`, but I was not able to override this in extension settings.

### Question
Is it possible that I have overlooked some configuration option that will allow me to override `--inspect-brk` with `--inspect` for all generated debug-related commands? And if not - is it possible to add some configuration option to do this?

### Additional Info

- VSCode Version: 1.50.1
- OS Version: Windows 10 Enterprise Version 1803
- Jest Runner Version v0.4.29

**Comment by firsttris** [comment]
similar to your other issue, i link it to the other one and close this one
https://github.com/firsttris/vscode-jest-runner/issues/166
