### ISSUE TITLE
[Feature Request?] Publish to the Open-VSX registry

### ISSUE THREAD

**Issue by orvisevans** [firsttris/vscode-jest-runner#122]
Can this extension be published to the Open VSX registry as well?

Open VSX registry: https://open-vsx.org/
How to Publish an Extension: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

This would allow users from VSCodium, Gitpod, Theia, etc. to also use it.

vscode-jest issue discussing the same thing: https://github.com/jest-community/vscode-jest/issues/602

**Comment by firsttris** [comment]
hey @orvisevans i didn't know. thx for this information. i will publish it to VSX

**Comment by firsttris** [comment]
https://open-vsx.org/extension/firsttris/vscode-jest-runner

**Comment by firsttris** [comment]
it still say my namespace is not valid, seems i made an error creating the namespace.
