### ISSUE TITLE
[Feature Request] Add way of running a script as a "before run" that runs before Jest executes

### ISSUE THREAD

**Issue by kevjames3** [firsttris/vscode-jest-runner#123]
This issue was discovered while digging into this: https://github.com/nodejs/node/issues/20432

Effectively, I am trying to debug one test, but I need `NODE_EXTRA_CA_CERTS` to be set before Jest executes.  This variable cannot be set at runtime.

Currently, the workaround is to go to my Node Debug console in VSCode and set the variable there.  Then I can debug each individual test.  I notice that when I click "Debug", what is outputted a command line is generated.  I simply want to prepend a "before run" hook to where I can set an ENV before Jest executes.

**Comment by firsttris** [comment]
in settings with 

"jestrunner.debugOptions": {}

you can add stuff to the debug console... 

https://github.com/firsttris/vscode-jest-runner/blob/master/src/jestRunner.ts#L109

would it be possible to add a varialbe to the debug console using this feature?

**Comment by kevjames3** [comment]
So I tried this
```json
"jestrunner.debugOptions": {
       "argv": [" export NODE_EXTRA_CA_CERTS=resources/security/certificate.pem "]
    }
```

And what outputted was

```
Warning: Ignoring extra certs from `resources/security/certificate.pemcd`, load failed: error:02001002:system library:fopen:No such file or directory
```

For some reason, it is appending "cd".  Am I doing this right?

**Comment by firsttris** [comment]
refering to
https://create-react-app.dev/docs/debugging-tests/#debugging-tests-in-visual-studio-code

i think i should be simple as this
```
"jestrunner.debugOptions": {
       "env":{
            NODE_EXTRA_CA_CERTS: resources/security/certificate.pem
         }
    }
```
