### ISSUE TITLE
not support jestrunner.configPath in vscode workspace 

### ISSUE THREAD

**Issue by zhongzhong0505** [firsttris/vscode-jest-runner#126]
![image](https://user-images.githubusercontent.com/15847574/100419262-315d0a80-30bf-11eb-9572-907abed6c5b8.png)

**Comment by mgutz** [comment]
I found a workaround. Add `jestrunner.jestPath` setting to your `.code-workspace` file. For example

```json
{
  "folders": [
    {
      "name": "root",
      "path": "."
    },
    {
      "path": "packages/backend"
    },
    {
      "path": "packages/frontend"
    }
  ],
  "settings": {
    "files.exclude": {
      "packages": true
    },
    "jestrunner.jestPath": "node_modules/jest/bin/jest.js"
  }
}
```

I can debug again with pnpm

**Comment by basickarl** [comment]
Yea I'm getting the same issue. I have a custom jest config file which has a custom testMatch settings, doesn't seem to load "run | debug" above the test in vscode in the correct files.

**Comment by firsttris** [comment]
i think its just a batter of the naming of your config file:

https://github.com/firsttris/vscode-jest-runner/blob/master/src/jestRunnerConfig.ts#L111

please re-open if your issue still persists.
