### ISSUE TITLE
Support function.name in describe block

### ISSUE THREAD

**Issue by aciccarello** [firsttris/vscode-jest-runner#129]
To keep test names up to date with refactored code, I often use `describe(myClassOrFunction.name, () => {})` to name my tests. This doesn't work currently because it is not a string, however the name is easily determinable by removing `.name`. Would you accept a PR to support this?

See also [#87 (comment)](https://github.com/firsttris/vscode-jest-runner/issues/87#issuecomment-659265057)

**Comment by firsttris** [comment]
hey @aciccarello yes im happy about any PR's !
