### ISSUE TITLE
Can't attach debugger to a test with a ">" in the name

### ISSUE THREAD

**Issue by ffMathy** [firsttris/vscode-jest-runner#131]
It just won't attach. If I remove the ">" from the describe name, it works just fine.

**Comment by firsttris** [comment]
this is probably not escaped correctly here https://github.com/firsttris/vscode-jest-runner/blob/master/src/util.ts#L10

**Comment by ffMathy** [comment]
Why does that function exist? And if it's for general command-line sanitization, I assume there should be a better library for this out there that we can use?

**Comment by ffMathy** [comment]
That way, we also avoid Coding by Exception (https://en.wikipedia.org/wiki/Coding_by_exception).

**Comment by firsttris** [comment]
i think (if i remember correctly) we need to escape special characters for testname and path because jest expects a regex

https://jestjs.io/docs/en/cli#jest-regexfortestfiles

**Comment by ffMathy** [comment]
Can this be used? https://www.npmjs.com/package/regex-escape

**Comment by ffMathy** [comment]
Perhaps combined with a "beginning of string" and "end of string" sequence in the regex, to make it stronger, instead of a "contains".

**Comment by firsttris** [comment]
maybe better avoid new deps if its just one simple function. 
e.g. https://github.com/IonicaBizau/regex-escape.js/blob/master/lib/index.js

**Comment by ffMathy** [comment]
I actually disagree. Even if it's a small function, it's easier to get the latest security updates, patches and fixes to the function. If we copy it over, we lose that possibility.

On the other hand, it has very little reason to change, and doesn't seem to have a lot of issues open. It also seems fairly simple.

Those are just my 5 cents. I'll leave the rest up to you :pray:

**Comment by firsttris** [comment]
i don't think this is a function that regularly changes. 
we would introduce more security concern to our app by adding new deps, then by having a static function.

also my understanding is the library you proposed is also not escaping ">"

**Comment by ffMathy** [comment]
Makes sense (so similar to my second paragraph).

If it isn't, I doubt it's because it's a regex sequence. Perhaps it's a terminal-based sequence in bash or the like?

**Comment by firsttris** [comment]
im not sure, if you find out, im very happy about any pull-request :+1: 

you can just clone the project, install it, and start with Run -> Start Debugging.

**Comment by firsttris** [comment]
should be fixed in v0.4.39
