### ISSUE TITLE
Run and Debug icon (typically displayed above the test) disappears when using describe.each

### ISSUE THREAD

**Issue by curt3105** [firsttris/vscode-jest-runner#137]
Hi I love using Jest Runner! We noticed an issue recently when writing tests with jest. Typically, there is a link/icon above each test. As you already know the link is for running and debug specific tests. When you add a describe.each test within the scope of the outer describe, the link above tests disappears. If you remove the describe.each the links reappear above the tests. The describe.each tests seem to interfere with the link.
Thanks!

**Comment by firsttris** [comment]
hey @curt3105,

i think we need to update jest-editor-support to the latest version to enable this feature

https://github.com/firsttris/vscode-jest-runner/issues/55

**Comment by curt3105** [comment]
Sounds good, is that something I need to do on my end? Sorry I am still a little naive with this. 
Thanks

**Comment by curt3105** [comment]
Okay, I think I understand what you are saying now, it looks like in the https://github.com/firsttris/vscode-jest-runner/blob/master/package.json the jest-editor-support": "^27.2.0. What do we need to do to get that updated?

**Comment by firsttris** [comment]
we need to increase it to the latest version https://github.com/jest-community/jest-editor-support/blob/master/package.json#L3

and maybe we also need to adjust this method: https://github.com/firsttris/vscode-jest-runner/blob/master/src/util.ts#L13

**Comment by firsttris** [comment]
you can clone the repo

update the version 

npm install
Go to Menu "Run" => "Start Debugging"
open your project with the new vscode instance just open

verify everything is working as you expect it.

report back

**Comment by bottlezz** [comment]
I have tried updated the package, it generally, work fine, however , there are some issues.
For a table case with
![image](https://user-images.githubusercontent.com/2524509/105430911-79089a00-5c09-11eb-8f50-460fbad24224.png)
the first block, test name would be "testId : 1 , testName : test1"
however the test name one jest-editor-support generates is "testId : \$id , testName : \$testName". and this will match no test case. 
So for interpolated string test name, the solution would fail. A solution i have in mind is to replace $var with regexp (.*), but a evaluation to identify string interpolation on the test name would be involved for every test cases, not sure if that would be desirable.

**Comment by firsttris** [comment]
i think that should be fine.

**Comment by gregoryzh** [comment]
@firsttris 
Hi,
I have created a PR to resolve the naming string interpolation, please take a look
https://github.com/firsttris/vscode-jest-runner/pull/148

**Comment by firsttris** [comment]
can this issue be closed now ? since #148 is merged.
