### ISSUE TITLE
Set environment variables before running tests.

### ISSUE THREAD

**Issue by Nxtra** [firsttris/vscode-jest-runner#138]
How can I specify an environment variable that should be available during the execution of my tests?

Eg. I want to set the `AWS_DEFAULT_PROFILE` environment variable to run my test.

**Comment by firsttris** [comment]
take a look here:
https://github.com/firsttris/vscode-jest-runner/issues/123

**Comment by firsttris** [comment]
generally it should also be possible to define an alternative jest command

```
"scripts": {
  "test": "NODE_ENV=test jest"
},
```

than in your vscode config

"jestrunner.jestCommand": "npm run test --"

**Comment by Nxtra** [comment]
> generally it should also be possible to define an alternative jest command
> 
> ```
> "scripts": {
>   "test": "NODE_ENV=test jest"
> },
> ```
> 
> than in your vscode config
> 
> "jestrunner.jestCommand": "npm run test --"

Nice, that works for running. I found the debug config via the linked issue. 

For others coming here, to set env vars for run and debug:

**Setup**
`.vscode/settings.json`:
```
{
  "jestrunner.jestCommand": "npm run test --",
  "jestrunner.debugOptions": {
    "env": {
      "AWS_PROFILE": "your-profile"
    }
  }
}
```

`package.json`
```
scripts : {
  "test": "AWS_PROFILE=transit-dev jest",
}

```

**Comment by firsttris** [comment]
nice thx for your feedback
