### ISSUE TITLE
[Feature] Option to remove/hide/disable "Run | Debug" in editor 

### ISSUE THREAD

**Issue by metal-gabe** [firsttris/vscode-jest-runner#147]
This is pretty straightforward, I'm a shortcut user when it comes to running my tests, and having these links appear above every test/block just adds visual clutter. It would nice if I had the ability to hide them. :-) 

![jest-runner](https://user-images.githubusercontent.com/53348382/112028775-c748f500-8af5-11eb-84e7-4fd3001d3f80.png)

**Comment by firsttris** [comment]
there is already a option in the vscode settings to disable codeLens

jestrunner.disableCodeLens

**Comment by metal-gabe** [comment]
@firsttris yea, that doesn't seem to really be working. 

I have these settings: 

```
"jestrunner.codeLensSelector": "**/*.{bueller}.{bueller}",
"jestrunner.disableCodeLens": true,
``` 

But `debug` is still showing up. 

![jestrunner-code-lens](https://user-images.githubusercontent.com/53348382/114243843-2f933580-9942-11eb-9ac3-ba1cdc572366.png)

**Comment by robatron** [comment]
@metal-gabe , just figured out you have to reload the window / restart vscode after setting `disableCodeLens` to `true` for this to work
