### ISSUE TITLE
support pnp.cjs (yarn2)

### ISSUE THREAD

**Issue by stavalfi** [firsttris/vscode-jest-runner#155]
the latest yarn2 version (of master branch) is using pnp.cjs.

you should look for pnp.cjs or pnp.js to fully support this feature.

this feature is not published yet, but it will soon enough.

**Comment by firsttris** [comment]
i dont have much xp with pnp yet.

but somone implemented yarn 2 pnp support with this PR:

https://github.com/firsttris/vscode-jest-runner/pull/103

**Comment by stavalfi** [comment]
@alexkuc

**Comment by alexkuc** [comment]
Relates to https://github.com/yarnpkg/berry/pull/2286

**Comment by alexkuc** [comment]
@stavalfi @firsttris https://github.com/firsttris/vscode-jest-runner/pull/157

**Comment by stavalfi** [comment]
Thanks @alexkuc !
