### ISSUE TITLE
Clear terminal before running tests

### ISSUE THREAD

**Issue by Alex-Dinu** [firsttris/vscode-jest-runner#161]
Is there a way to clear the terminal and then run the tests? For example, how can I run [clear] and then the test command as usual.

I tried adding  [clear &&] as a Jest command, but that did not work.

Thanks

**Comment by firsttris** [comment]
acutally we are already clearing the terminal before executing the jest command.

https://github.com/firsttris/vscode-jest-runner/blob/master/src/jestRunner.ts#L200

**Comment by Alex-Dinu** [comment]
It must be my version then. I'm running VS Code 1.54.3 and Jest Runner 0.4.31. Unfortunately I cannot upgrade VS Code at this time.

Thank you for the quick response.
