### ISSUE TITLE
No tests found on Windows 10 using VS Code 1.31.1

### ISSUE THREAD

**Issue by infin8loop** [firsttris/vscode-jest-runner#17]
On Windows, `regexForTestFiles` jest parameter is generated with an absolute path that uses backslashes `\`.  This causes no matching test files to be found.  Changing the backslashes to forward slashes `/` causes it to work.  

This behavior is new and it might coincide with the latest update to VS Code (1.31.1).  Has there been a change to the way that VS Code returns the file path?  Or perhaps it's related this jest issue: https://github.com/facebook/jest/issues/6546?

**Comment by gpascual2** [comment]
I think this might be also related to this issue: [https://github.com/facebook/jest/issues/3793](https://github.com/facebook/jest/issues/3793)

It is a regex matter parsing the path to the while in windows. One solution that worked for me is changing the path to use forward slashes as reported above. Also works scapping the back slashes in the path using the double backslash `\\`  as  `node "c:\myproject\node_modules\jest\bin\jest.js" "c:\\myproject\\src\\some_folder\\file.test.ts" -t "spec-title"`

**Comment by infin8loop** [comment]
Thanks for the link to the related issue.  Yeah, escaping the backslashes works as well, as does removing the path to use only the file name.  However, having to edit the generated command in any way takes all the goodness out of this super handy extension.  It's probably just a matter of needing to re-parse the file path that is returned by `editor.document.fileName` to get around the regex issue?

**Comment by zhaoxuyll** [comment]
https://github.com/firsttris/vscode-jest-runner/pull/19

**Comment by firsttris** [comment]
fixed with https://github.com/firsttris/vscode-jest-runner/pull/19
