### ISSUE TITLE
Pin "Run/ Debug" words above the code

### ISSUE THREAD

**Issue by rodrigocnascimento** [firsttris/vscode-jest-runner#173]
Hi,

There's a way to pin the words "run/ debug" above the code on the use cases? My code keeps jumping and it's a little annoying. 

![image](https://user-images.githubusercontent.com/24860/118289749-08cd9f00-b4ac-11eb-8ae2-56b640046f1d.png)

Thanks,

**Comment by Christilut** [comment]
Just had this too. It seems to remove the "Run | Debug" whenever there is a linting error. And a linting error happens during normal typing so the page is constantly jumping. Very annoying.

Can the "Run | Debug" just always be there? Regardless of errors.

**Comment by firsttris** [comment]
should be fixed in v0.4.35.

please re-open if your issue persists.

**Comment by kamatheuska** [comment]
Can we reopen this? it's still happening on v0.4.44

**Comment by Christilut** [comment]
Seems to be happening again with v0.4.47

**Comment by Christilut** [comment]
Reverting to 0.4.35 works.

Can we re-open this issue?

**Comment by amandapouget** [comment]
Is still an issue in 0.4.47 can confirm.

**Comment by amandapouget** [comment]
Reverting to 0.4.37 did not work for me.

**Comment by jamietre** [comment]
Is there any workaround for this? It's basically unusable to have it enabled while editing tests.

**Comment by BrutalSimplicity** [comment]
It is much more than mildly annoying when you're starting from a blank test template. It would be great to maybe only re-render on save or something, if it's not possible to fix. It seems like you might also be able to avoid re-renders when the file is not "parseable".

fwiw, I've seen the same issue in the Python testing suite and believe they offer a setting to only run render on save to help.
