### ISSUE TITLE
When debugging, Can't find Can't find Node.js binary "node": path does not exist...

### ISSUE THREAD

**Issue by jjm340** [firsttris/vscode-jest-runner#175]
With the latest version of VSCode, I just started receiving the error message: 
Can't find Node.js binary "node": path does not exist. Make sure Node.js is installed and in your PATH, or set the "runtimeExecutable" in your launch.json.

This worked fine up until the last update of VSCode it seems.

**Comment by firsttris** [comment]
re-open if issue still persists with version 0.4.38

**Comment by jjm340** [comment]
Problem went away on it's own!

**Comment by jjm340** [comment]
Is this option documented? If not, might be nice to have it there.

**Comment by floroz** [comment]
> For anyone else having this issue this was how I fixed it in my use-case.
> Add to your user/workspace settings:
> 
> ```json
>     "jestrunner.debugOptions": {
>       "runtimeExecutable": "/absolute/path/to/node"
>     }
> ```
> 
> This was on extension `v0.4.44`, with `node` available in my terminal and the `vscode-jest-runner` `run` command working but the `debug` command failing with the above error message, and vscode running the workspace from a remote ssh env

Thank you, had the same issue and this solved it for me!
