### ISSUE TITLE
Run/debug buttons placed at wrong position & associated with wrong test name

### ISSUE THREAD

**Issue by LinqLover** [firsttris/vscode-jest-runner#180]
Consider [this file](https://github.com/LinqLover/downstream-repository-mining/blob/a489715130f11dea88b1aea8f3d94a0f6115d7f4/test/references.test.ts):

![image](https://user-images.githubusercontent.com/38782922/120463074-d375ec00-c39b-11eb-88e6-8f88e23ecb09.png)

The buttons are placed at the wrong position in the test, and if I press the Run button, jest will be invoked like this in the console so no tests will be run at all:

```sh
node '/workspace/downstream-repository-mining/node_modules/.bin/jest' '/workspace/downstream-repository-mining/test/references\.test\.ts' -t 'getNpmDeps'
```

Apparently, the heuristic (?) that is used to find the jest cases does not cover my rather uncommon test file here ... :-)

**Comment by firsttris** [comment]
it should still work if you directly "right click" on the describe text and use the context-menu options. (with some kind of fallback solution)

**Comment by LinqLover** [comment]
Confirmed. So this is officially a low-level issue.

(Haha, I just noticed that I used the "Jest Test Explorer" for this before. :-) It does not have such a nice editor integration as this project, but the debugger integration is a bit better IMHO. For example, if I run an `expect()` assertion in the debugging console, with vscode-jest-runner, I see `[2m` artifacts in the output, whereas when using "Jest Test Explorer", jest appears to know that it is not printing to a TTY. Just a notice. :-))

**Comment by firsttris** [comment]
can you post a example screenshot of what you explained?

**Comment by firsttris** [comment]
check v0.4.43 if the behaviour has improved?

before there was a bug where the codelens options (run,debug) where placed at the wrong position.
question: was this also related to your issue, and is fixed now?

regards
tristan

**Comment by firsttris** [comment]
re-open if this issue still persists
