### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by cyclops24** [firsttris/vscode-jest-runner#182]
- Issue Type: `Bug`
- Extension Name: `vscode-jest-runner`
- Extension Version: `0.4.35`
- OS Version: `Linux x64 5.6.0-1055-oem`
- VS Code version: `1.56.2`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 237,
		"activateCallTime": 0,
		"activateResolvedTime": 23,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "firsttris.vscode-jest-runner",
				"_lower": "firsttris.vscode-jest-runner"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```

Today when I try to run my test whole VSCode freezez. I can take this screenshot after a lot of try:
![Screenshot from 2021-06-03 13-27-41](https://user-images.githubusercontent.com/8266479/120637824-a7c43600-c46f-11eb-87ef-9d62bc35bb94.png)

**Comment by uberspeck** [comment]
I'm seeing the same issue. I was working on unit tests until an hour ago and suddenly Jest Runner stopped responding.

**Comment by firsttris** [comment]
can you check if this still happens with 0.4.38?

**Comment by uberspeck** [comment]
@firsttris I looks like `0.4.38` fixes the issue 👍

**Comment by cyclops24** [comment]
Thanks guys for your quick response and fix.
Yeah, It's totally fixed now :wink:
