### ISSUE TITLE
Parsing of test files with casting broken again since 0.4.36

### ISSUE THREAD

**Issue by mvindahl** [firsttris/vscode-jest-runner#189]
This worked in 0.4.33, broke in 0.4.34, worked again in 0.4.35, and seems to have been broken since 0.4.36. Screenshots below are using 0.4.39.

It affects Typescript test files containing casts. As far as I can see, it prevents parsing of the file, causing codelens run/debug buttons not to be updated.

Example:

Minimal and meaningless test file after a clean restart of VSCode:
![image](https://user-images.githubusercontent.com/5991804/121658514-b0d18a80-caa1-11eb-84cc-c9a9ec7f66ce.png)

Removing the offending line immediately causes the codelens buttons to appear. These work as expected.
![image](https://user-images.githubusercontent.com/5991804/121658555-ba5af280-caa1-11eb-9c89-f40a19a23643.png)

Reintroducing the offending line will not cause the codelens buttons to disappear. (But restarting VSCode will).
![image](https://user-images.githubusercontent.com/5991804/121658576-c0e96a00-caa1-11eb-8553-6ce7126715e7.png)

I suspect, however, that the button locations have just been cached from the last successful parsing of the file. Altering the structure of the file will cause the buttons to render in unexpected places:
![image](https://user-images.githubusercontent.com/5991804/121658654-d363a380-caa1-11eb-874c-5da87bcf5898.png)

**Comment by firsttris** [comment]
hey @mvindahl thx for reporting

**Comment by firsttris** [comment]
@mvindahl check 0.4.40

**Comment by mvindahl** [comment]
I installed 0.4.44 (the most recent version) and it works like a charm 👍

Thanks for taking the time to fix this 🙂
