### ISSUE TITLE
Compatibility with jest 27

### ISSUE THREAD

**Issue by JLP0578** [firsttris/vscode-jest-runner#191]
Hello,
First of all, thank you for developing this extension.

I wanted to tell you about a problem.
On my project was installed Jest 27.
I tried to install your vscode extension to use Jest combined with Enzyme.
I got an error: 
![image](https://user-images.githubusercontent.com/54902345/122568098-b30b8a00-d049-11eb-8ca5-2b8d56247804.png)

To fix the problem temporarily I downgraded the version of Jest to 25 and everything works.

Sincerely.
JLP

**Comment by firsttris** [comment]
i think this is more related to Enzyme then Jest or my Extension.

some side note/tip:
most people use react-test-library before enzyme today

**Comment by JLP0578** [comment]
Thank you for your reply. I will then look for the enzyme.
