### ISSUE TITLE
With VS code version 1.21 debug is not working

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [firsttris/vscode-jest-runner#2]
I have installed February upadte of vscode version 1.21 and Debugger stopped to owrk
with version 1.20.1 debugger command is this:
& 'node' '--inspect-brk=7001' '--inspect-brk' 'some root path/node_modules/jest/bin/jest.js' '-i' '-t' ' get descri'

with 1.21 it adds ${workspaceRoot} in 'some root path/${workspaceRoot}/node_modules/jest/bin/jest.js'

and error says that jest.js cannot be found on this path

however running tests works fine.

I have downgraded to 1.20.1 it start to work again

**Comment by CapLonelyFlaw** [comment]
+1. Need fix fot vscode 1.21.

**Comment by firsttris** [comment]
released 0.21 which should fix debug-mode for 1.21
please report back
tristan

**Comment by vytautas-pranskunas-** [comment]
Also with new version of this plugin i started to get this error:

Error: Cannot find module 'C:\c:\Development\...\node_modules\jest\bin\jest.js'

this double C:\c:\ thingy

I tried on 2 machines.

**Comment by firsttris** [comment]
i guess you are on windows?

**Comment by vytautas-pranskunas-** [comment]
Yes

**Comment by firsttris** [comment]
but this  C:\c:\ only happens when using Run correct?

Debug is working?

**Comment by vytautas-pranskunas-** [comment]
Yes, but debug was working perfectly just yesterday but today it says: No tests found

**Comment by vytautas-pranskunas-** [comment]
Actually after updating vscode and jest versions to latest
Paths are incorrect for both Debug and Run commands
Debugger is not attaching to actual test

**Comment by firsttris** [comment]
i think i have found the path issue. please re-check 0.2.2

**Comment by vytautas-pranskunas-** [comment]
yes, that fixed problems with paths but:
Debug do not hit break points. It shows that attaches but does not hit

**Comment by firsttris** [comment]
```
        {
            "name": "Debug Jest Tests",
            "type": "node",
            "request": "launch",
            "program": "${workspaceFolder}/node_modules/jest/bin/jest.js",
            "args": [
                "-i",
                "-t", "removeById",
            ],
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen"
        }
```
this is a 100% valid debug profile for jest.
strang thing is my debug profile does not hit breakpoints on Windows, but on Linux, OSX it works. 

can you verify ?

**Comment by firsttris** [comment]
also tried an older version debug profile... but it also does not hit break-points on windows
```
        {
            "name": "Debug Jest Tests",
            "type": "node",
            "request": "launch",
            "args": [
               "--inspect-brk",
               "${workspaceFolder}/node_modules/jest/bin/jest.js",
                "-i",
                "-t", "removeById",
            ],
            "console": "integratedTerminal",
            "internalConsoleOptions": "neverOpen"
        },
```

**Comment by firsttris** [comment]
its a vscode issue
https://github.com/Microsoft/vscode/issues/45657
