### ISSUE TITLE
failed to run tests in Create-React-App

### ISSUE THREAD

**Issue by cyberixae** [firsttris/vscode-jest-runner#20]
I'm having problems running my tests with Jest Runner. I think this happens because the tests are written in TypeScript and the test files have `.ts` and `.tsx` extensions instead of `.js` and `.jsx`.

**Comment by firsttris** [comment]
i think this is an issue with your jest-config

< root >/jest.config.js
```
module.exports = {
  globals: {
    "ts-jest": {
      tsConfigFile: "./packages/app/tsconfig.json"
    },
    '__CONFIG__': 'local'
  },
  verbose: true,
  testURL: "http://localhost/",
  clearMocks: true,
  resetMocks: true,
  collectCoverage: true,
  collectCoverageFrom: ["**/app/src/components/**"],
  coveragePathIgnorePatterns: [".d.ts"],
  testRegex: "(/test/.*)\\.(test|spec)\\.(ts|tsx|js)$",
  testPathIgnorePatterns: [
    "/node_modules/",
    "/dist/",
    "/coverage/",
    "/webpack/"
  ],
  transformIgnorePatterns: [
    "/node_modules/",
    "/dist/",
    "/coverage/",
    "/webpack/"
  ],
  watchPathIgnorePatterns: [
    "/node_modules/",
    "/dist/",
    "/coverage/",
    "/webpack/"
  ],
  setupFiles: ["./packages/app/.build/jest/enzymeSetup.js"],
  snapshotSerializers: ["enzyme-to-json/serializer"],
  setupTestFrameworkScriptFile: "mock-local-storage",
  moduleFileExtensions: ["ts", "tsx", "js", "jest"],
  moduleNameMapper: {
    "\\.(css|scss)$": "identity-obj-proxy"
  },
  transform: {
    "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$":
      "<rootDir>/packages/app/.build/jest/fileTransformer.js",
    "^.+\\.(ts|tsx)$": "ts-jest"
  }
};
```

**Comment by cyberixae** [comment]
The application was created with `create-react-app` and the tests would typically be run with `react-scripts test`. There is no jest configuration file since one is not required for running the tests through that command. Can I somehow tell Jest Runner to use their default configuration file?

**Comment by firsttris** [comment]
Thats a very interesting topic !

do we know where this default configuration file resides?

there a vscode config option for the plugin to do this

jestrunner.configPath | Define an external jest-config path to jest (from ${workFolder} e.g. jest-config.json)
-- | --

regards
Tristan

**Comment by firsttris** [comment]
please let me know if this works for you. would be nice if the plugin works with create-react-app.

regards
Tristan

**Comment by cyberixae** [comment]
The Jest configuration is never written to a file. It is generated at run time. See https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/scripts/test.js#L77

So as long as you're using create-react-app it is impossible to fix the problem by linking to a configuration file. However, there is an _eject_ action for projects who want to stop using create-react-app. Running eject should remove create-react-app from the project and replace it with static configuration files. Migrating away from create-react-app is of course not an easy decision.

**Comment by DevelAx** [comment]
From my experience it works fine with TS.

**Comment by firsttris** [comment]
maybe vscode-jest-runner can just execute "react-scripts test"

is it possible to add the same parameters as for jest?

**Comment by adi518** [comment]
Was about to post a similar issue. The solution to this would be a `jestCommand` option, that will support an alternative command (other then the default `jest` to run Jest. As said, with CRA, everything in abstracted away, so we can't naively run `jest` and expect it to work. I think adding this option should be fairly straight forward. 👍

**Comment by firsttris** [comment]
thx @adi518 
happy to merge your other ideas as well

**Comment by firsttris** [comment]
this is possible now with 0.3.6
