### ISSUE TITLE
Feature Proposal - Add a menu to launch test in watch mode

### ISSUE THREAD

**Issue by ajubin** [firsttris/vscode-jest-runner#202]
Besides `debug` and `run`, it could be useful to be able to quickly launch test in watch mode

**Comment by PindaPixel** [comment]
Would personally like to see it work with Test Explorer UI, but not sure how much that is to ask.

**Comment by ajubin** [comment]
@firsttris any update for this pr ?

**Comment by firsttris** [comment]
sorry mate, i was so bussy :( 

good work, i reviewed your PR

**Comment by firsttris** [comment]
merged

**Comment by ajubin** [comment]
Hi, thanks for the merge :) 

After some thoughts, I find it useful to have a debug codeLens because I run my tests more often in watch mode as in debug mode. 
Maybe this could be configured via settings.

For instance, instead of this

```
"jestrunner.disableCodeLens": false
```


we could have something like this : 
```
"jestrunner.codeLens": ["run", "watch", "debug"]"
```

whats your opinion ?

**Comment by firsttris** [comment]
sounds good
