### ISSUE TITLE
Debug not working

### ISSUE THREAD

**Issue by CobaltCoder** [firsttris/vscode-jest-runner#208]
When I try to debug a test with yarn pnp enabled I just get an error that says:
 Cannot find module 'C:\Projects\xxx\.yarn\releases\yarn-*.cjs'

It is there and named yarn-3.0.1.cjs

**Comment by CobaltCoder** [comment]
I fixed it by adding this in jestRunner.ts

    if (this.config.isYarnPnpSupportEnabled) {
      config.args = ['jest'];
      if(!this.config.jestBinPath)
        config.program = '.yarn/releases/yarn-*.*js';
    }

I can do a PR if you like.

**Comment by firsttris** [comment]
i think there is already a fix commited but no new version released.
https://github.com/firsttris/vscode-jest-runner/commit/aeaaebe950f2615ad00239f5a3b885bcc23e6b1c

please re-open if the issue still persists in 0.45 and above
