### ISSUE TITLE
Can't work with two test suites

### ISSUE THREAD

**Issue by DevelAx** [firsttris/vscode-jest-runner#21]
I have 2 test suites: unit-tests & e2e-tests. The first one is defined in the `package.json` and it works by default with Jest Runner. The second has a separate config file and therefore Jest Runner can't find it. So when I set the `"jestrunner.configPath"` parameter the second test suite start working, but the first one stops.

Is it possible to make both test suites work without changing the configuration file path every time?

**Comment by firsttris** [comment]
i think it should be possible to have something like multiple profiles, with each profile you have a different jest config. 

but of course this would involve some work.

**Comment by firsttris** [comment]
it would be easy to create another "run jest" context menu entry which always runs without config and another who always runs with config.

it's just a question how such a feature could be implemented in a useful manner.

without modifying the code i don't think its possible...

**Comment by firsttris** [comment]
now supporting multiple workspaces with vscode, maybe this fixes your issue.
