### ISSUE TITLE
Feature Request: Please add `run tests in file` menu back

### ISSUE THREAD

**Issue by jimsleon** [firsttris/vscode-jest-runner#212]
There was a menu `run tests in file` before, I forgot from which version it was removed. without this menu,you have to right click at the beginning of the file or the end of the file(or some where not in a test case) to run all tests in the file. which is not convenient because you might need to scroll first to do it. with the old menu 'run tests in file', you can do it by right click at any place in the file.   (This was extremely annoying when there was a bug with jest `each`)

SO PLEASE ADD IT BACK.

**Comment by firsttris** [comment]
its still there, just open the command palette strg+shift+p and search for "jest file".

i just dont want to flood the command menu with to many options.

**Comment by firsttris** [comment]
are you happy with this option?
