### ISSUE TITLE
wrong breakpoints behavior when debugging

### ISSUE THREAD

**Issue by TalTurjeman20** [firsttris/vscode-jest-runner#216]
Hi,
Since the last update of VScode
When I try to debugging, I clicked on debug button of one of the tests,
new file opened with own breakpoints organized.
The expected result its to debug the breakpoint in the same file like always .
Attachment added.

![jestRunnerConfig](https://user-images.githubusercontent.com/80334668/133926045-b66c915f-7761-4ff4-8e9b-1aa232a037ae.png)

![new file](https://user-images.githubusercontent.com/80334668/133926481-5126face-06cb-4627-a385-78b67277c704.png)

![AfterDebugClick](https://user-images.githubusercontent.com/80334668/133926049-9ed18b3d-3fdd-4d83-ac09-98f97f4ed101.png)

**Comment by firsttris** [comment]
i think its not related to the extension, if you issue still persists re-open the issue.
