### ISSUE TITLE
Not able to add Node Options --experimental-vm-modules in debug

### ISSUE THREAD

**Issue by selvakumar-invicara** [firsttris/vscode-jest-runner#217]
We follow ESM, so to make jest to be work I used below command,

`node --experimental-vm-modules node_modules/.bin/jest`

I have given this command in `jestrunner.jestCommand` to make jest runner to work for RUN. But It doesn't work for debug and never seeing any options pass this argument. If I add it in debugOptions then it append it as below 

` /usr/local/bin/node ./node_modules/.bin/jest --experimental-vm-modules` 

which gives an error as the argument should be before jest.

Is there any way to solve this problem

**Comment by eltoroit** [comment]
Hi,

Can you please share your settings (package.json, settings.json, jest-config.json, etc). I am trying to set this up using *.mjs files and I can't debug them with this extension.

I am getting this error: `Cannot use import statement outside a module`

**Comment by Crono1981** [comment]
Like @eltoroit , I could really use a `settings.json` sample file.

Right now, it's as if `jestrunner.*` settings were ignored altogether. I even tried giving `jestrunner.jestPath` an unexisting path just to make sure it fails; it didn't.
