### ISSUE TITLE
[Feature Request] Shortcuts

### ISSUE THREAD

**Issue by lonix1** [firsttris/vscode-jest-runner#22]
Please add shortcut support, so we can map "run test" and "debug test"? Any default would be okay.

I would use:
<kbd>alt-1</kbd> for run test
<kbd>alt-2</kbd> for debug test

And once this [feature request](https://github.com/firsttris/vscode-jest-runner/issues/15) is added, I would use:
<kbd>alt-3</kbd> for repeat last run test
<kbd>alt-4</kbd> for repeat last debug test

These shortcuts are available in Visual Studio, one of the few things I miss about it!

**Comment by lonix1** [comment]
I see there are already shortcuts available... just not documented! :laughing: 

That is a wonderful feature. You might want to add it to the documentation... Thanks!

**Comment by firsttris** [comment]
@lonix1 

Can you tell how it works and what to document?

or even better contribute the documentation :smiley_cat:

**Comment by lonix1** [comment]
File -> Preferences -> Keyboard Shortcuts -> click "{}" on top right to open json config file
then add:
````
{
  "key": "alt+1",
  "command": "extension.runJest"
},
{
  "key": "alt+2",
  "command": "extension.debugJest"
},
````

Then I can run the extension using those shortcuts!

**Comment by firsttris** [comment]
thx!

**Comment by lonix1** [comment]
no... thank you! :)

**Comment by firsttris** [comment]
added to readme
