### ISSUE TITLE
run test.js when editing index.js

### ISSUE THREAD

**Issue by astanet** [firsttris/vscode-jest-runner#223]
Thank you for really great extention.

I always use test file named "test.js" for "index.js" in the same directory.
I want to run "test.js" when editing "index.js" without switching editor tab to "test.js".
Is there a way to do this?

In [Code Runner](https://github.com/formulahendry/vscode-code-runner), it can be configured as follows
```
  "code-runner.executorMapByGlob": {
    "index.js": "cd \"$workspaceRoot\" && npm test $dirtest.js",
  }
```

Thanks.

**Comment by firsttris** [comment]
there is currently no way todo this with my extension, and my understanding is that this is exacly what vscode-jest does.
