### ISSUE TITLE
flaw

### ISSUE THREAD

**Issue by klover2** [firsttris/vscode-jest-runner#225]
Something went wrong：
jest-editor-support parser returned error SyntaxError: Decorators cannot be used to decorate parameters. (18:20)

eg: 
`
@Injectable()
class TestService {
  protected async findAll(): Promise<number[]> {
    return [1, 2, 3, 4, 5];
  }
  async mutexTTLKey(@LockKey() key: string): Promise<number[]> {
    return await this.findAll();
  }
}

describe('lock decorator', () => {})
`

The above error will occur when @LockKey() exists

I am using nestjs

**Comment by dreamerblue** [comment]
same issue, also this case fails too so that CodeLens will be broken:

```typescript
@A().B()
class Test {}
```

**Comment by dnsritch** [comment]
me too, when I use parameter decorator，
the "run | debug" button disappear

<img width="531" alt="image" src="https://user-images.githubusercontent.com/22022298/154070258-ac5ef11b-7429-4d83-ac74-aab62b59491f.png">

<img width="558" alt="image" src="https://user-images.githubusercontent.com/22022298/154070313-d5556323-8edb-4f82-81c6-2bb3f767b201.png">

**Comment by firsttris** [comment]
check new version which includes new version of jest-editor-support.

please re-open if this issue still persists.
