### ISSUE TITLE
Asking for sudo password

### ISSUE THREAD

**Issue by Christilut** [firsttris/vscode-jest-runner#226]
I'm using WSL2 and Jest has been asking me for my sudo password whenever I try to run a test. It didn't used to do this, started a while ago (few months maybe). 

In the terminal that launches it just shows the normal `node` command with the jest arguments. No sudo anywhere. But the prompt wants me to enter my sudo password. Not going to do that of course.

If I use that same terminal and ctrl+c out of the sudo question, I can run the original node command without problems.

**Comment by firsttris** [comment]
i have no clue how to fix it, sorry
