### ISSUE TITLE
Option to run the command on external native terminal

### ISSUE THREAD

**Issue by Avivbens** [firsttris/vscode-jest-runner#228]
Hey, really like the extension.
I'm looking for a way to run the command on an external terminal, so no space will be taken from the code editor. 

Thanks a lot!

**Comment by YogeshUmeshVaity** [comment]
This will definately make the extension more useful for people like me who like to work in full screen for code and separate terminal for running tests.

**Comment by firsttris** [comment]
pull request welcome if you know how to achieve this.

**Comment by Avivbens** [comment]
https://github.com/firsttris/vscode-jest-runner/pull/258
