### ISSUE TITLE
enable overwrite in config for config.program

### ISSUE THREAD

**Issue by magnusdunker** [firsttris/vscode-jest-runner#229]
The hard coded value (config.program = '.yarn/releases/yarn-*.*js') does not work on windows. It needs the full filename

![image](https://user-images.githubusercontent.com/713853/148792615-b0c05128-f79f-4e66-ac39-f332adf0eb07.png)

This can be fixed by changing the filename to the full filename in /dist/extension.js

Would be nice to be able to overwrite this value or even better if the extension figures out the filename it self

**Comment by magnusdunker** [comment]
The problem is the file name (yarn-*.*.js) which on my windows should be yarn-3.1.1.cjs for it to work.

Ill make a PR

Thanks
Magnus

**Comment by firsttris** [comment]
Have you tried with Powershell? Other shells was working with * escaping.

magnusdunker ***@***.***> schrieb am Do., 13. Jan. 2022,
08:18:

**Comment by magnusdunker** [comment]
Yes, im using powershell as teminal in VS code

**Comment by Othreumaru** [comment]
I'm getting same issue, though coming from different perspective. When using yarn workspaces with ```folke.vscode-monorepo-workspace``` plugin for vs-code, yarn will not be accessible from .yarn/releases/yarn-*.*js when a sub-root directory is used.

So having an option to set ```config.program``` would solve the issue I think.

**Comment by firsttris** [comment]
i think we fixed this, please re-open if the issues persists.
