### ISSUE TITLE
Resolving to jest executable defaults to first folder in current workspace | automatically detect workspace subproject to find jest executable

### ISSUE THREAD

**Issue by PBug90** [firsttris/vscode-jest-runner#23]
When using a workspace with multiple projects, the test runner executes jest from the first folder in the current workspace if no explicit jest executable path had been configured:

https://github.com/firsttris/vscode-jest-runner/blob/b7839ea8c000b13b5b264b90ce8705da0c3adc47/src/extension.ts#L15

Is there any way to change that so it detects the correct workspace project that the file of the currently executed test resides in?

**Comment by firsttris** [comment]
there shoud be a way of getting the active workspaceFolder or the workpaceFolder number/index.

in the documentation if found getWorkspaceFolder but probably thats not what we need here ..

https://code.visualstudio.com/api/references/vscode-api

**Comment by PBug90** [comment]
Added a PR: #25

**Comment by firsttris** [comment]
thx!

**Comment by firsttris** [comment]
fixed
