### ISSUE TITLE
Newer TypeScript type import syntax breaks UI

### ISSUE THREAD

**Issue by rraziel** [firsttris/vscode-jest-runner#233]
Hello,

I am not quite confident this issue comes from `vscode-jest-runner` and not some Jest configuration down the line, but might as well start somewhere. However running tests from the command line works alright.

Using the newer syntax for TypeScript type imports removes the `Run | Debug` options around `describe()`, `it()`, etc.:

```ts
import type { X } from 'y';
//     ^ works fine
import { type X } from 'y';
//       ^ breaks
```

I noticed that the TypeScript version referenced in [package.json is 4.4.2](https://github.com/firsttris/vscode-jest-runner/blob/master/package.json#L210), while this feature was [added in TypeScript 4.5](https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/#type-on-import-names).

Also great job on this extension, it has already saved me an estimated billion hours (I'm not good at estimations).

**Comment by Cellule** [comment]
Parsing is handled by jest-editor-support so I'm guessing/hoping that #239 would cover this

**Comment by Cellule** [comment]
I managed to make jest-editor-support@30 work locally and it was able to properly parse `import { x} from 'y'`

**Comment by firsttris** [comment]
check new vscode-jest-runner which includes new jest-editor-support version.

please close if issue is fixed.

**Comment by Cellule** [comment]
![image](https://user-images.githubusercontent.com/4157103/157477102-e453ad80-6955-4717-bd0f-2d02d088259c.png)

Confirmed it works with updated extension :D
