### ISSUE TITLE
RFC: automated release cycle

### ISSUE THREAD

**Issue by cdaringe** [firsttris/vscode-jest-runner#242]
# Problem

I want some of the recent goodies checked into this ext, but they are not published to the marketplace.

# Discussion

Do you have any interest in setting up some sort of Continuous Delivery to publish on change? I haven't looked into extension publishing, but would be willing to help wire up some `semantic-release` action to possibly help facilitate it if there is sufficient interest.

**Comment by firsttris** [comment]
i think thats possible, i just need to add the key/cert to the security context of the git repo.

will look into that

**Comment by firsttris** [comment]
we would need to add another release step to our github action workflows:

documentation:
https://code.visualstudio.com/api/working-with-extensions/continuous-integration#github-actions-automated-publishing


i added the vsce pat as VSCE_PAT to the repository secrets. 

so if you find time i would be very happy.

regards
Tristan

**Comment by cdaringe** [comment]
Got it working in my fork.

https://github.com/cdaringe/vscode-jest-runner/runs/5797929175?check_suite_focus=true

Patches inbound. Pretty straightfoward

**Comment by cdaringe** [comment]
moving convo to #246
