### ISSUE TITLE
jest-runner version in marketplace is outdated and missing jestrunner.yarnPnpCommand config

### ISSUE THREAD

**Issue by moro85** [firsttris/vscode-jest-runner#243]
I'm unable to use the jestrunner.yarnPnpCommand as current published version in marketplace is outdated.
This config which is present in github master should unblock scenarios for debugging tests with yarn v3 workspace
Could you please publish a new version to the marketplace?

**Comment by firsttris** [comment]
will do

**Comment by firsttris** [comment]
done
