### ISSUE TITLE
Use the test name, instead of the file path, to reference a test

### ISSUE THREAD

**Issue by gustavo80br** [firsttris/vscode-jest-runner#264]
My typescript tests need to call "test-name.test" so it's able to find the right javascript file in the dist/ folder. I found no way to use the plugin because I couldn't customize the way to reference a test, except by its full file path. Is there a way to overcome this problem, or write a settings that can make sens in this case? Thanks

**Comment by Avivbens** [comment]
Please attach some code examples for better review of the problem
