### ISSUE TITLE
Debug & Run are displayed in some test files but not others

### ISSUE THREAD

**Issue by GP4cK** [firsttris/vscode-jest-runner#267]
Hello,
I'm working with this monorepo: https://github.com/TriPSs/nestjs-query
When I open the root in VSCode,
1. If I open `packages/query-typeorm/__tests__/module.spec.ts`, then I can see "Run" and "Debug" above `describe` and `it`.
2. However if I open `packages/query-typeorm/__tests__/services/typeorm-query.service.spec.ts`, then I can't

How may I troubleshoot this? I tried commenting / deleting all the tests except one to see if it was a file size issue (1,997 lines) but that didn't work...

**Comment by GP4cK** [comment]
One workaround I found was to add this .vscode/launch.json:

```json
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug Jest Tests",
      "type": "node",
      "request": "launch",
      "runtimeArgs": [
        "--inspect-brk", 
        "${workspaceRoot}/node_modules/.bin/jest", 
        "--runInBand",
        "-t",
        "set the relation to null", // replace with name of test
      ],
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen"
    }
  ]
}
```

**Comment by firsttris** [comment]
there is a codeLensSelector option


jestrunner.codeLensSelector | CodeLens will be shown on files matching this pattern (default **/*.{test,spec}.{js,jsx,ts,tsx})
-- | --

probably have something todo with this

**Comment by GP4cK** [comment]
Actually it seems it's working now on v0.4.56.
Thanks for the help though.
