### ISSUE TITLE
Ability to pass along command line arguments

### ISSUE THREAD

**Issue by ddehghan** [firsttris/vscode-jest-runner#27]
For some reason passing --coverage to jest was breaking our tests. I really wanted to this while debugging. So I had to fork and make my own hacky version of this extension. 

Unfortunately I dont know enough about vscode extensions to be able to submit a pull request. But it seems not too hard have another setting where users can add their own command line arguments and the extension would just append them at the end.

Thanks for the extension. I use it every day

**Comment by firsttris** [comment]
hey @ddehghan 

can you push the changes to your fork on github? 

git add .
git commit -m "command line arguments"
git push

I could create a Pull-Request from your fork then.

regards
Tristan

**Comment by firsttris** [comment]
good idea

**Comment by firsttris** [comment]
@ddehghan do you want to provide any intel what you did, so we can fix it as well?

**Comment by ddehghan** [comment]
I think we need is the ability modify the final string that gets executed. so that people can modify it and insert their on parameters in it. a regex would be most flexible option.

**Comment by firsttris** [comment]
i just found out it actually already works for the debug mode

![image](https://user-images.githubusercontent.com/1709260/65178713-9ba90280-da59-11e9-9c44-f4a29c309e5e.png)

check https://github.com/firsttris/vscode-jest-runner/issues/39

**Comment by firsttris** [comment]
hey,
this is now available with 0.4.4

example settings:

"jestrunner.runOptions": [
"--coverage",
"--colors"
]

for debug

"jestrunner.debugOptions": {
"args": [
"--no-cache",
"--watch",
"--watch-all"
],
}
