### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'html') at new JSDOMEnvironment 

### ISSUE THREAD

**Issue by luisaverza** [firsttris/vscode-jest-runner#274]
**Problem**
My project is configure to use `testEnvironment: 'jsdom',` so when I run the tests with vscode-just-runner I find this error:
```
  - Test suite failed to run

   TypeError: Cannot read properties of undefined (reading 'html')

   at new JSDOMEnvironment (../../node_modules/jest-environment-jsdom/build/index.js:72:44)
  ```

It is a [known problem](https://stackoverflow.com/questions/72169503/typeerror-cannot-read-properties-of-undefined-reading-html) after updating jest from v27 to v28
The solution will be pretty much to add the `jest-environment-jsdom` library. I could send a PR adding the lib but I'm not sure if this could impact others that don't use jsdom environment.

**Comment by firsttris** [comment]
hey @luisaverza 

is it enough to add jest-environment-jsdom to your project, or do we need to add it to vscode-jest-runner extension?

at the end jest-runner is just creating the cli command to execute jest.

but jest and everything is used from your acutal project.

please provide feedback :+1:

**Comment by luisaverza** [comment]
Hey @firsttris thanks for you quick reply!
Yes, you are right. Since I work in a monorepo I was having a hard time configuring jest-runner.
After setting the ProjectPath and the right jest command, everything is running great! Thanks ✅
