### ISSUE TITLE
Extension opens new terminal although its terminal still exists

### ISSUE THREAD

**Issue by shaman-apprentice** [firsttris/vscode-jest-runner#292]
# Bug

## Expected behavior
GIVEN a vscode-jest-runnter terminal is open
WHEN running tests through the extension
THEN the existing vscode-jest-runnter terminal gets used

## Actual behavior
Under certain conditions vscode-jest-runner creates a new terminal

## Steps to reproduce
1. Open a terminal
2. Run a tests through the extension -> a vscode-jest-runner terminal gets created
3. Close the terminal from step one
4. Run a test through the extension -> a new vscode-jest-runner terminal gets created, although the one from step 2 still exists

## Thanks saying
Thanks in general for this nice extension! It improves my workflow :)

**Comment by firsttris** [comment]
thx mate
