### ISSUE TITLE
The run command fails because a space...

### ISSUE THREAD

**Issue by mdelgadov** [firsttris/vscode-jest-runner#3]
Hello, I like your extension but is only working half of it.
I can run debug command but can't make it run the test.
It crashes with this message:

jest.js -t 'can load instance'
module.js:549
    throw err;
    ^

Error: Cannot find module 'c:\Users\mdelg\Documents\Visual'
    at Function.Module._resolveFilename (module.js:547:15)

The problem is that I'm in Visual Studio 2017 because the backend resides in a project there.

I tried to configure in package.json this jestrunner.jestPath and jestrunner.configPath parameters with ho success...
Any ideas on what to do?

Thanks in advance...

**Comment by firsttris** [comment]
Hello,

so you really mean Visual Studio not VSCode ? (i was not aware that this is even possible)

jestPath and configPath chould be absolut path to jest executable and jest config.

regards
Tristan

**Comment by firsttris** [comment]
actually it takes the path from the vscode library:
https://github.com/firsttris/vscode-jest-runner/blob/master/src/extension.ts#L21

**Comment by firsttris** [comment]
or you can use the one defined in your config:
https://github.com/firsttris/vscode-jest-runner/blob/master/src/extension.ts#L16

**Comment by firsttris** [comment]
can you re-try with version 0.2.3 ?

**Comment by NagRock** [comment]
Got same issue:

```$ node c:\MY_APP_DIR\node_modules\jest\bin\jest.js -t "should have create new dashboard option as first on a list"
module.js:540
    throw err;
    ^

Error: Cannot find module 'c:\workspaces\angular\angular.server\workspacesangularangular.servernode_modulesjestbinjest.js'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

Looks like the path is added twice. Once with backslashes and once without `c:\workspaces\angular\angular.server\workspacesangularangular.servernode_modulesjestbinjest.js`
