### ISSUE TITLE
Debugging fails if test name contains `(`, `)`, possibly more

### ISSUE THREAD

**Issue by ManfredLange** [firsttris/vscode-jest-runner#30]
We have a test that is specified as follows:
```
it("(true)", () => {
   // ... test implementation
}
```
When using `Debug Jest` to run this, the extension falls over with the following error message:
> syntax error near unexpected token `('

This could probably be fixed by always surrounding value for the `-t` parameter with single quotes. Instead of
```
... --inspect-brk=35753 node_modules/.bin/jest -i /lambda/src/parser/parser.micro.ts -t (true)
```
this would work:
```
... --inspect-brk=35753 node_modules/.bin/jest -i /lambda/src/parser/parser.micro.ts -t '(true)'
```

While at the moment we observe this for parenthesis only, it is possible that other special characters may cause a similar problem.

Note that we can run jest normally, so we believe this is a problem with how this extension crafts the command line for jest. Also choosing `Run Jest` surrounds that parameter value with single quotes, e.g.
```
node '/lambda/node_modules/.bin/jest' '/lambda/src/parser/parser.micro.ts' -t '(true)'
```

Our setup:
- VS Code version 1.36.1
- vscode-jest-runner version 0.3.6

**Comment by firsttris** [comment]
@ManfredLange 
Thx for your report!

i try to reproduce your issue:

```
  it("(true)", async () => {
    const hours = await ComplainCollection.getHoursByDate('1234', '2017-10-01');
    expect(hours).toBe('0');
  });
```

```
╰─>$ node '/home/firsttris/Projects/timetracking-app/node_modules/.bin/jest' '/home/firsttris/Projects/timetracking-app/packages/server/src/collections/ComplainCollection.test.ts' -t '(true)'
 PASS  packages/server/src/collections/ComplainCollection.test.ts
  ComplainCollection Test
    ✓ (true) (18ms)
```

but the test passes.

also tried with single quotes in the test name

vscode-jest-runner version 0.3.6

On which OS are you? 
Which Terminal are you using? (.e.g. powershell, bash, cmd, fish)

**Comment by firsttris** [comment]
@ManfredLange the quotes are missing, u are right.

**Comment by firsttris** [comment]
it think we need to quote() here https://github.com/firsttris/vscode-jest-runner/blob/master/src/extension.ts#L115

like we did for the normal run here
https://github.com/firsttris/vscode-jest-runner/blob/master/src/extension.ts#L60

**Comment by firsttris** [comment]
fixed
https://github.com/firsttris/vscode-jest-runner/commit/353b4b4feb998cc17ba550061da17cf02b1aee15

in version version 0.3.8

```
╰─>$ cd /home/firsttris/Projects/timetracking-app ; /usr/bin/node --inspect-brk=39416 node_modules/.bin/jest -i '/home/firsttris/Projects/timetracking-app/packages/server/src/collections/ComplainCollection.test.ts' -t '(true)' 
Debugger listening on ws://127.0.0.1:39416/c1eda623-d1ab-4568-8c42-c4fa6a905ba4
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
[ts-jest][DEPRECATED] - replace any occurrences of "ts-jest/dist/preprocessor.js" or  "<rootDir>/node_modules/ts-jest/preprocessor.js" in the 'transform' section o
f your Jest config with just "ts-jest".
 PASS  packages/server/src/collections/ComplainCollection.test.ts
  ComplainCollection Test
    ✓ (true) (20ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        5.101s
Ran all test suites matching /\/home\/firsttris\/Projects\/timetracking-app\/packages\/server\/src\/collections\/ComplainCollection.test.ts/i with tests matching "(true)".
Waiting for the debugger to disconnect...
fish: “/usr/bin/node --inspect-brk=394…” terminated by signal SIGKILL (Forced quit)
```

**Comment by firsttris** [comment]
please re-open if the issue still exists.

regards
Tristan
