### ISSUE TITLE
Multiple tests run when I only choose one to be tested

### ISSUE THREAD

**Issue by diego-pan** [firsttris/vscode-jest-runner#304]
I'm experiencing a situation where when I choose to Run, or Debug a single test, it actually runs two tests.

For example, when I choose Debug here:

<img width="332" alt="image" src="https://user-images.githubusercontent.com/112917963/227375942-87f006c3-ccce-4817-9115-b2a97916db48.png">

It will run the test I chose, and the one below it. If seems to pick up this second test based on the test description string -- since they both begin with similar text: "creates a user account".

```
describe('Test a module', () => {
    test('creates a user account', () => {
        // ..... test code here
    });

    test('creates a user account without an address', () => {
        // ..... test code here
    });
});
```

Is this by design? Is there a configuration option that I could tweak so only tests I choose are run?

**Comment by hnrchrdl** [comment]
I think what we would need here is to make the `-t` param more precise.
the runner adds `-t 'creates a user account'`, which in your example matches both test cases. maybe better would be `-t '^creates a user account$'`.

**Comment by firsttris** [comment]
i think this pull-request https://github.com/firsttris/vscode-jest-runner/pull/282 contains what you need?

**Comment by hnrchrdl** [comment]
> i think this pull-request #282 contains what you need?

exactly
