### ISSUE TITLE
Fails to debug with `\` in test name

### ISSUE THREAD

**Issue by ManfredLange** [firsttris/vscode-jest-runner#31]
We have a test specified like this:
```
it("1000 > \$blah", () => {
   // ...
}
```
Choosing `Debug Jest` from the context menu on "it" results in the following command line:
```
cd /lambda ; /usr/local/bin/node --inspect-brk=47749 node_modules/.bin/jest --no-cache -i /lambda/src/parser/parser.micro.ts -t "1000 > \\$blah" -i /lambda/src/parser/parser.micro.ts -t "1000 > blah" -i /lambda/src/parser/parser.micro.ts -t "1000 > \\$blah" -i /lambda/src/parser/parser.micro.ts -t "1000 > \\$blah"
```
Note how the `-i` flag is provided multiple times instead of only once. `-i` in this case should be specified only once.

The test fails with the following error message:
```
SyntaxError: Invalid regular expression: /1000 > \,1000 > blah,1000 > \,1000 > \/: \ at end of pattern
    at new RegExp (<anonymous>)
```

Environment:
- VS Code, version 1.36.1
- Jest Runner, version 0.3.6
- Node JS, version 10.16.0
- Debian Linux, version 9.9

**Comment by firsttris** [comment]
Hey @ManfredLange 
Thx for your report.

Tried to reproduce this issue as well.

```
  it("1000 > \$blah", async () => {
    const hours = await ComplainCollection.getHoursByDate('1234', '2017-10-01');
    expect(hours).toBe('0');
  });
```

```
╰─>$ cd /home/firsttris/Projects/timetracking-app ; /usr/bin/node --inspect-brk=8205 node_modules/.bin/jest -i /home/firsttris/Projects/timetracking-app/packages/server/src/collections/ComplainCollection.test.ts -t "1000 > \\$blah" 
Debugger listening on ws://127.0.0.1:8205/a122ce22-1f36-46a3-86df-420cc29a4b69
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
 FAIL  packages/server/src/collections/ComplainCollection.test.ts
  ● Test suite failed to run

    SyntaxError: Invalid regular expression: /1000 > \/: \ at end of pattern
        at new RegExp (<anonymous>)

      at node_modules/jest-jasmine2/build/index.js:123:29

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.905s
Ran all test suites matching /\/home\/firsttris\/Projects\/timetracking-app\/packages\/server\/src\/collections\/ComplainCollection.test.ts/i with tests matching "1000 > \".
Waiting for the debugger to disconnect...
fish: “/usr/bin/node --inspect-brk=820…” terminated by signal SIGKILL (Forced quit)
```

**Comment by firsttris** [comment]
@ManfredLange i only get the i flag once. 

does not look if the issue comes from the extension?

is the command in my test correct?

**Comment by firsttris** [comment]
@ManfredLange i think i found the issue, but don't know how to fix it yet

it seems the vscode debugger is automatically adding double quotes to words in the "args" string if they contains spaces.

my code is now checking if the testName contains spaces and in this case im not quoting it.

but vscode debugger also escape / with // and we can't influence this. 

at least i think we can't

means "1000 > $blah" or '1000 > $blah' is working now

but 

"1000 > \$blah" results in "1000 > \\$blah"

which can't be resolved

**Comment by firsttris** [comment]
i also found that the normal "Run" skips all tests with "$" inside it.
but it seems that comes from jest itself.

**Comment by ManfredLange** [comment]
`$` is used for interpolation in `sh`, `bash`, etc. So as a result if you use something like `$foo==10` as the name of the test, then the shell will turn it into `==10` since generally variable `$foo` is undefined. To avoid interpolation it's possible to escape `$` for the shell command line with a backslash, e.g.  `\$foo==10`.

I also noticed that using parenthesis trips up the regex as well, e.g. test name of `(var(foo) + var(bar)) lt 5000`. This is possibly the downside of using regular expressions for finding tests.

Regarding how to solve it: My suspicion is that perhaps using regular expressions in this context causes problems and a proper parser might be needed. Another option could be to plug into the language services of the TS Server. I haven't investigated the latter in detail, though, so can't say for sure.

**Comment by ManfredLange** [comment]
@firsttris Yes, I realize that there are things beyond your control, Tristan. :-)

Perhaps this helps: Going back to jest's docs I realized that the value for jest's `-t` parameter is a regular expression ([docs](https://jestjs.io/docs/en/cli#testnamepattern-regex)). `-t` is short for `--testNamePattern=<regex>`. This means that if the test label contains characters that have special meaning in regular expressions, they need to be escaped. For example, this includes `(`, `)`, `\`, `$`, `^`, and similar more. So a potential solution could be to escape those characters in the selected test's lable and pass it to jest's command line only after that.

**Comment by firsttris** [comment]
Oh thats why it was not working for me, didn't thought about -t was a regex.

Is then everything whats "under our control", fine so far?

**Comment by firsttris** [comment]
Hey @ManfredLange all special characters will be escaped now. check version 0.4.3. closing this issue now.
