### ISSUE TITLE
No run buttons on *.*-spec.ts files

### ISSUE THREAD

**Issue by oitan** [firsttris/vscode-jest-runner#310]
We have `*.api-spec.ts`, `*.e2e-spec.ts` files, and those have no run or debug buttons, which usually do appear above  `test()`, `spec()`, `describe()` jest function.

**Comment by whalemare** [comment]
@oitan are you trying to override `jestrunner.codeLensSelector` property described in readme.md file in this repository?

**Comment by oitan** [comment]
@whalemare it worked. Thank you. I promise I read `readme.md`, just didn't notice.
