### ISSUE TITLE
Does not work with .cjs files

### ISSUE THREAD

**Issue by mike247** [firsttris/vscode-jest-runner#313]
Jest config files can have multiple filenames 
```
jest.config.js|ts|mjs|cjs|json
```

Jest runner only seems to support .js or .ts as valid extensions (see https://github.com/firsttris/vscode-jest-runner/blob/master/src/jestRunnerConfig.ts#L111)

There is an open PR from last year to add .cjs to the config, can this please be merged?

https://github.com/firsttris/vscode-jest-runner/pull/281/files

**Comment by firsttris** [comment]
should work now, if not re-open please.
