### ISSUE TITLE
Debug with CRA - How to setup

### ISSUE THREAD

**Issue by PhilippeRoy** [firsttris/vscode-jest-runner#315]
The [recommendation](https://github.com/firsttris/vscode-jest-runner#debugging-jsxtsx-with-cra) on how to get `debug` to work in a Create React App can be simplified by only requiring you to update the `jestrunner.debugOptions` to the following:

```json
  "jestrunner.debugOptions": {
    "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/react-scripts",
    "runtimeArgs": [
      "test",
      "${fileBasename}",
      "--runInBand",
      "--no-cache",
      "--watchAll=false",
      "--color"
    ]
  },
```

**Comment by firsttris** [comment]
thanks i will put your finding into the readme

**Comment by SnowNooDLe** [comment]
This saved my life so much! Many thanks!
