### ISSUE TITLE
"Run Jest" contextual menu no longer working on whole file, since 0.4.62

### ISSUE THREAD

**Issue by etiennepoirier2005** [firsttris/vscode-jest-runner#324]
With previous versions, I could right-click anywhere on a file, but outside a test, and select "Run Jest" to run tests for whole file (or whole "describe" section).
Since version 0.4.62, "Run Jest" does nothing if not done inside a test (inside a "it"). Happens with versions 0.4.62, 0.4.63 and 0.4.64
Thank you.
![image](https://github.com/firsttris/vscode-jest-runner/assets/54073453/b2a8b2b0-1e6d-4d14-8a16-bdb2bdbafb3b)

**Comment by firsttris** [comment]
hey @etiennepoirier2005  thanks for reporting this issue.

this is then probably related to https://github.com/firsttris/vscode-jest-runner/pull/301

because this was the change from 0.4.62

 i will revert this change for now.

**Comment by tristan-ctream** [comment]
check 4.65

**Comment by firsttris** [comment]
should be fixed in 0.4.65

**Comment by etiennepoirier2005** [comment]
Hello Tristan,
I confirm it's working again.
Thank you, that was fast! :)

**Comment by firsttris** [comment]
@domsleee, he fixed it.
