### ISSUE TITLE
Debug Test doesn't support multiply-nested test

### ISSUE THREAD

**Issue by aagranovExtend** [firsttris/vscode-jest-runner#326]
What works is initiating the debug on the top-level `describe`, or an `it` 1-level below the `describe`. If there are nested describe blocks lower than that 1st-level, initiating debug on the test will not work.

The debugger never attaches.

# Environment
node: v18.17.0
OS: macOS Ventura 13.5
vscode-jest-runner: v0.4.66

**Comment by domsleee** [comment]
Do you mean like this?

```javascript
describe('nested', () => {
  describe('a', () => {
    it('b', () => {
      expect(true);
    });
  });
});
```

This scenario seems to work for me

**Comment by cdaringe** [comment]
3+ months stale without repro. please reopen with example if required
