### ISSUE TITLE
Unable to detect correct config when it is jest.config.json

### ISSUE THREAD

**Issue by zsstiers** [firsttris/vscode-jest-runner#328]
It looks like the issue is probably just not having the .json extension listed on
https://github.com/firsttris/vscode-jest-runner/blob/e3f7c76334c248ff426fd078a7634213b4106174/src/jestRunnerConfig.ts#L114

**Comment by domsleee** [comment]
Thanks for the report 👍 

Agree, it looks like this case this missing

https://jestjs.io/docs/configuration

> The file will be discovered automatically, if it is named `jest.config.js|ts|mjs|cjs|json`
