### ISSUE TITLE
No Tests Found on Windows 10 using VSCode 1.82.2 - Backslashes in file name

### ISSUE THREAD

**Issue by ScottSEA** [firsttris/vscode-jest-runner#333]
[This stackoverflow post](https://stackoverflow.com/q/77129008/127888) goes into greater detail, but the gist of it is when clicking the "run test" button on a file or test, the `testPathPattern` path has unwanted backslashes in the file name, e.g.
```
"--testPathPattern" "c:\\\\git\\\\appName\\\\src\\\\test\\\\util\\\\someFile\\.test\\.ts"
```
instead of 
```
"--testPathPattern" "c:\\\\git\\\\appName\\\\src\\\\test\\\\util\\\\someFile.test.ts"
```

> Windows Version: Win10 Pro v22H2
> VSCode Version: 1.82.2
> Jest Extension Version: v5.2.3

**Comment by domsleee** [comment]
Hello, based on the version number, I think you are using a different extension ([Orta.vscode-jest](https://marketplace.visualstudio.com/items?itemName=Orta.vscode-jest)).

I would suggest raising an issue with [vscode-jest](https://github.com/jest-community/vscode-jest/issues)

**Comment by domsleee** [comment]
Oh, I see you already did https://github.com/jest-community/vscode-jest/issues/1070 😄 

I will close this one 👍
