### ISSUE TITLE
Tips for using with bun?

### ISSUE THREAD

**Issue by benjick** [firsttris/vscode-jest-runner#338]
Hey

I'm wondering if anyone has gotten this to work well with `bun test` yet? I can't get it to just run the test I'm actually clicking run on, and I keep having to start it manually from the command line

Sorry for raising an "issue" but I couldn't think of a better-suited place to post
Cheers

**Comment by firsttris** [comment]
there are certain places in the source where node is used.
https://github.com/firsttris/vscode-jest-runner/blob/master/src/jestRunner.ts#L171
https://github.com/firsttris/vscode-jest-runner/blob/master/src/util.ts#L89

maybe its possible i dont know.

havent used bun yet.

best regards
tristan

**Comment by firsttris** [comment]
you can clone the repo change the code and start extension in development mode:
https://github.com/firsttris/vscode-jest-runner#steps-to-run-extension-in-development-mode

**Comment by victmo** [comment]
A few months later, but an alternative is to set `jestrunner.jestCommand` in your project settings to `bun test` and the extension will use Bun.

*path/to/project/.vscode/settings.json*
```json
{
  "jestrunner.jestCommand": "bun test"
}
```
