### ISSUE TITLE
RFC: Run from nearest package.json

### ISSUE THREAD

**Issue by cdaringe** [firsttris/vscode-jest-runner#340]
# Problem

In monorepos, some modules are only available in the sub-package under test, thus aren't available if `cwd` the monorepo root. 

For example:

```txt
<root>
  packages/
     foo/
       package.json
       __tests__/
         foo.spec.ts
     bar/
       package.json
       __tests__/
         bar.spec.ts
```

If cwd is `<root>`, and `foo.spec.ts` calls jest.mock on a package that is only present `packages/foo/node_modules`, jest crashes!

# Discussion

- it is common for monorepo users to open their project from the `<root>`
- it is common for monorepo users to try and exec a test from a child package from the VSCode root workspace ctx
- the aforementioned CWD mismatch can lead to this ext crashing (no fault of the extension)

Support for a feature like `cwdNearestPackageJson: true` could easily:

- discern the spec filename under test
- find the nearest package.json filename
- set the cwd to the dirname of the prior found package.json filename

With such a feature, monorepo users could run a test from any sub-package, and reliably run in the same pwd and node_modules context as if they had just `cd <path-to-package> && jest .`!

**Comment by domsleee** [comment]
I'll reopen this one for discussion 👍 

I think this case is already supported, but I could be wrong.

If you try it with  `jestrunner.changeDirectoryToWorkspaceRoot`, it will run `cd <path>` before running the jest command.

You can see here it is falling back to `currentPackagePath`, which upsearches for `package.json`:

https://github.com/firsttris/vscode-jest-runner/blob/43cc89b213698c2971b8b3437345ad6d04b1eb6d/src/jestRunnerConfig.ts#L51-L77

Based on the code, perhaps the current docs could be improved:
<html>
<body>


jestrunner.changeDirectoryToWorkspaceRoot | Changes directory to workspace root before executing the test
-- | --



</body>
</html>

I think this setting should really be:
> Changes directory to the resolved project path. The fallback order is `jestrunner.projectPath`, falling back to the nearest `package.json`, falling back to the workspace root.

Does this cover your use case? Thanks
