### ISSUE TITLE
Cannot use import satement outside a module

### ISSUE THREAD

**Issue by cesar-rl** [firsttris/vscode-jest-runner#359]
I'm using Typescript and I'm getting this error just out of the box. When I run from the CLI, jest runs ok.

Does someone knows how to allow imports using this extension?

**Comment by firsttris** [comment]
Hey the extension is simply generating a command which is executed from CLI.
So it should be pretty much the same as when you execute Jest from CLI.

there is nothing which prevents you from using import statements.

**Comment by cesar-rl** [comment]
I think I got the problem.

In my project, config files are not in the root folder, so I need to pass the `--config <PATH>` to Jest in the CLI.  Is there a way to inform the extension the path to the config file? Or to add the `--config <PATH>`  to the Jest CLI calls?

In the CLI:
![image](https://github.com/firsttris/vscode-jest-runner/assets/163411110/242ef10d-0fb3-434d-8ac9-c0ba67a61f59)

Using the extension:
![image](https://github.com/firsttris/vscode-jest-runner/assets/163411110/267b0b40-3c83-47cd-80e6-a51519bab660)

**Comment by cesar-rl** [comment]
I saw on [this issue](https://github.com/firsttris/vscode-jest-runner/issues/346) that the extension looks all the way up from the current folder, buit in my case it is in a way down, so it would need to be informed as a configuration.
Could I contribute in this? Or is it already done?

**Comment by firsttris** [comment]
https://github.com/firsttris/vscode-jest-runner?tab=readme-ov-file#extension-settings

there is a extension setting for this jestrunner.configPath

**Comment by cesar-rl** [comment]
Thanks, it did the job. Now I have a problem with the reporter, I'll search for any issues about the subject.
