### ISSUE TITLE
How to use it with yarn workspaces and ts-jest

### ISSUE THREAD

**Issue by keycad** [firsttris/vscode-jest-runner#37]
Hi,
I've tried your extension, but I can't get it working in VS Code having yarn workspaces and ts-jest (my project is written in TypeScript).
I have an app structured as follows:

Main folder
- package.json (containing workspaces definition)
- tsconfig.json (containing general config)
- module1
    - package.json (containing own module dependencies)
    - tsconfig.json
- module2
    - package.json (containing own module dependencies)
    - tsconfig.json
- app
    - package.json (containing own module dependencies)
    - tsconfig.json

In each of the modules, I have ts jest tests.

When I try to debug one test with your tool, I get the following message:

c:\repos\Main>cd c:\repos\Main && "C:\Program Files\nodejs\node.exe" --inspect-brk=11419 node_modules\jest\bin\jest.js -i """c:/repos/Main/module1/src/utils/__tests__/myTests.spec.ts""" -t """getText"""
Debugger listening on ws://127.0.0.1:11419/aa7023ee-f5dd-4430-80d6-fe70be4e098b
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
No tests found
In C:\repos\Main
  54 files checked.
  testMatch: **/__tests__/**/*.js?(x),**/?(*.)+(spec|test).js?(x) - 0 matches
  testPathIgnorePatterns: \\node_modules\\ - 54 matches
Pattern: "c:\\repos\\Main\\module1\\src\\utils\\__tests__\\myTests.spec.ts" - 0 matches
Waiting for the debugger to disconnect...

Any help would be great, thanks in advance

**Comment by firsttris** [comment]
hey @keycad 

using yarn workspaces in my projects as well.

if you open the mono repository in vscode you might need a jest config in the root directory

jest looks from the directory its extecuted recursivly for a jest config, it seems in your case it can't find one, thats why it can't find the tests.

but thats acutally not a issue if the vscode addon. the addon is just executing jest.

my projects might look like this
![image](https://user-images.githubusercontent.com/1709260/63057241-16767f00-beea-11e9-81a5-9dd21a3ab691.png)
(keep in mind that the config could be not update to date, its some older project)

i extend tsconfig from the root directory:

![image](https://user-images.githubusercontent.com/1709260/63057692-188d0d80-beeb-11e9-9154-ec9af74641ab.png)

i try to have most configs in root to not have duplicates.

if ithis mono repo would contain projects written in different langauges this approach would not work, in this case it would be better to just open the one project in vscode not the mono repo.

hope this helps
Tristan

**Comment by firsttris** [comment]
@keycad does this answer your question and i can close your issue? or do you still think something is wrong?

**Comment by firsttris** [comment]
my current jest config for this project looks like this:

jest.config.js
```
module.exports = {
    moduleDirectories: [
      "node_modules",
      "packages/common",
      "packages/app/src"
    ],
    collectCoverageFrom: [
      "**/server/src/**"
    ],
    preset: 'ts-jest'
  }
```

**Comment by keycad** [comment]
I couldn't look this until now, but it works smoothly, thanks :)

**Comment by firsttris** [comment]
give the project a star if you like it :)
