### ISSUE TITLE
Run Debug Jest fails for CMD and GIT bash

### ISSUE THREAD

**Issue by Shurna83** [firsttris/vscode-jest-runner#38]
Hello,
thanks for this VSCode extension, I find it really useful.

Unfortunately, I cannot make Debug Jest command work.

I can fire Run Jest on my test and it works fine.
It produces this output:

```
node "d:/DEV/SDP/sales_portal_master/node_modules/jest/bin/jest.js" "d:/DEV/SDP/sales_portal_master/sales_sdp_gui/fx/services/fx-drafts-chain-store.spec.ts" -t "subscribe: no draft yet, empty one is given"
```

But if I fire Debug Jest, it fails with this output:

```
$ "C:\\Program Files\\nodejs\\node.exe" --inspect-brk=7972 node_modules\\jest\\bin\\jest.js -i \"d:/DEV/SDP/sales_portal_master/sales_sdp_gui/fx/services/fx-drafts-chain-store.spec.ts\" -t "subscribe: no draft yet, empty one is given"
Debugger listening on ws://127.0.0.1:7972/41c4a8e8-153d-4010-bc8f-4991de6e7343
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
jest-haste-map: duplicate manual mock found: fx-mocks
  The following files share their name; please delete one of them:
    * <rootDir>\sales_sdp_gui\__tests__\__mocks__\fx-mocks.ts
    * <rootDir>\target\js\sales_sdp_gui\__tests__\__mocks__\fx-mocks.js
 
jest-haste-map: duplicate manual mock found: gui-state-stub
  The following files share their name; please delete one of them:
    * <rootDir>\sales_sdp_gui\__tests__\__mocks__\gui-state-stub.ts
    * <rootDir>\target\js\sales_sdp_gui\__tests__\__mocks__\gui-state-stub.js

No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In D:\DEV\SDP\sales_portal_master
  2847 files checked.
  testMatch: **/?(*.)(spec|test).ts?(x) - 151 matches
  testPathIgnorePatterns: \\node_modules\\ - 2847 matches
  testRegex:  - 0 matches
Pattern: "d:\\DEV\\SDP\\sales_portal_master\\sales_sdp_gui\\fx\\services\\fx-drafts-chain-store.spec.ts" - 0 matches
Waiting for the debugger to disconnect...
```

Here is my jest.config.js file

```
 const path = require("path");
 
 module.exports = {
     preset: "ts-jest",
     setupFiles: ["<rootDir>/tests_gui/global-test-setup.ts"],
     testEnvironment: "jsdom",
     testURL: "http://localhost",
     rootDir: "./",
     transform: {
         ".(ts|tsx)$": "ts-jest",
         ".mail$": "jest-raw-loader"
     },
     testMatch: ["**/?(*.)(spec|test).ts?(x)"],
     snapshotSerializers: ["enzyme-to-json/serializer"],
     moduleNameMapper: {
         "^.+\\.(css|less|scss|html)$": "identity-obj-proxy",
         "ionweb-react": path.join(__dirname, "./src/mocks/ionweb-react")
     },
     globals: {
         "ts-jest": {
             // diagnostics: {
             //     ignoreCodes: [2531, 2532, 2722, 2743, 7005, 7006, 7008]
             // },
             diagnostics: true
         }
     }
 };
```

Here is my VSCode about:

```
Version: 1.37.1 (user setup)
 Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
 Date: 2019-08-15T16:17:55.855Z
 Electron: 4.2.7
 Chrome: 69.0.3497.128
 Node.js: 10.11.0
 V8: 6.9.427.31-electron.0
 OS: Windows_NT x64 10.0.17763
```
I tried also to run debug manually by trying different arguments (removing the double quotes from test file path, for instance), but not luck.

Thanks for your support!

**Comment by jefjef** [comment]
I am currently experiencing the same issue. 
Running without debugging works fine, with debugging i get '0 matches' on Pattern.

**Comment by alonrbar** [comment]
Same issue here :(

```
c:\Users\Alon\Documents\devel\easy-template-x>cd c:\Users\Alon\Documents\devel\easy-template-x && "C:\Program Files\nodejs\node.exe" --inspect-brk=48008 node_modules\jest\bin\jest.js -i """c:/Users/Alon/Documents/devel/easy-template-x/test/fixtures/text.tests.ts""" -t "removes empty tags"
Debugger listening on ws://127.0.0.1:48008/0e20a544-e4fa-424f-bbc7-b20aa86fec57
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In C:\Users\Alon\Documents\devel\easy-template-x
  81 files checked.
  testMatch:  - 0 matches
  testPathIgnorePatterns: \\node_modules\\ - 81 matches
  testRegex: \\test\\.*[.]tests[.]ts$ - 10 matches
Pattern: "c:\\Users\\Alon\\Documents\\devel\\easy-template-x\\test\\fixtures\\text.tests.ts" - 0 matches
Waiting for the debugger to disconnect...
```

**Comment by firsttris** [comment]
hey i just tested on my machine (linux)

and debug seemed to work and hits the breakpoint.

![image](https://user-images.githubusercontent.com/1709260/65177291-b9289d00-da56-11e9-98db-805a714bba40.png)

maybe its a problem for windows? i will double check.

if you know how to solve this issue, please do not hesitate to poste your solution or create a PR

**Comment by firsttris** [comment]
Test on Windows 10 works as well:

![test windows10](https://user-images.githubusercontent.com/1709260/65266537-8d1f2180-db13-11e9-8c63-bcbf206e9b2d.PNG)

my jest config:
https://github.com/firsttris/react-track/blob/master/jest.config.js

test file:
https://github.com/firsttris/react-track/blob/master/packages/server/src/collections/ComplainCollection.test.ts

🤷‍♂ can not find any issue

**Comment by tuur29** [comment]
Using Powershell as a default shell does indeed fix this on windows. The problem happens when using CMD or Git bash as the default terminal. Perhaps a setting for an independant default terminal might be a solution here? (Might also be a nice way to apply a custom look to your tests).

**Comment by firsttris** [comment]
thx @tuur29 for finding the issue

> Perhaps a setting for an independant default terminal might be a solution here? (Might also be a nice way to apply a custom look to your tests).

i like you idea, do you know how to do this?

**Comment by tuur29** [comment]
Seems like you can set a custom shellPath and extra arguments when opening a new terminal: https://code.visualstudio.com/api/references/vscode-api#window.createTerminal

Perhaps you could allow us to set these variables in the extension settings? No clue about the specifics though, I have yet to create my own VSCode extension.

**Comment by alonrbar** [comment]
Hi,

Love your extension and used it until this issue started happening. 
When it did, I found this other great extension called [Daddy-Jest](https://github.com/DevelAx/Daddy-Jest).

The thing is, now I have both installed. I use Daddy Jest for debugging tests and this extension for running test without debugging.
Maybe you can join forces or at least learn from each other...

@firsttris @DevelEx

**Comment by firsttris** [comment]
hey @alonrbar 
don't know whats your issue, but this one is simple. 
just use powershell - and everything works fine.
it's the best terminal for windows anyway.

if you want to improve stuff - code & contribute.

**Comment by firsttris** [comment]
So you have to configure you vscode to use powershell, which is in most cases the default option anyway.
I also put this in the Readme: https://github.com/firsttris/vscode-jest-runner#known-issues
