### ISSUE TITLE
Test cases with overlapping names are run accidentally

### ISSUE THREAD

**Issue by ThomasR** [firsttris/vscode-jest-runner#40]
Say I have three test cases,

`it('renders')`,
`it('renders errors')`
`it('sometimes renders')`

If I want to run the first test, the plugin produces the command line parameter `-t renders`, which runs all three tests.

This is because the argument to `-t` is a regular expression that is matched against the full test name (which is obtained from concatenating all `describe`s and the test name, separated by spaces).

**Comment by mikaoelitiana** [comment]
@ThomasR  @firsttris would using exact match regex pattern be an acceptable soluction? The output would be something like `... -t "^renders$"`.

**Comment by ThomasR** [comment]
You need to combine all describe blocks and escape special characters.

For example:

```
describe('.save()', () => {
  it('saves stuff' /*…*/)
});
```

should result in `"^\\.save\\(\\) saves stuff$"`

**Comment by mikaoelitiana** [comment]
@ThomasR I see. I will update the PR.

**Comment by firsttris** [comment]
why would it not be sufficient if it would result in
`^saves stuff$`

?

**Comment by ThomasR** [comment]
@firsttris 

> Note: The regex is matched against the full name, which is a combination of the test name and all its surrounding describe blocks.
https://jestjs.io/docs/en/cli#testnamepattern-regex

so the test name in this case is `".save() saves stuff"`, and thus `^saves stuff$` does not match.

**Comment by PizzaPartyInc** [comment]
Any estimation on this fix? :)

**Comment by firsttris** [comment]
hey @PizzaPartyInc we are still looking for a volunteer who takes care of this :)

will take a look at this once i find time between my work for enterprise cyber consortiums.

regards
tristan

**Comment by firsttris** [comment]
hey,
implemented it like @ThomasR pointed out. check version 0.4.3.

some implementation details:
if you select a test within a describe it will do a exact match with fullpath `"^\\.save\\(\\) saves stuff$"`
but if you just click on a describe it will not do a exact match. (since you probably want to execute all tests within the describe)

if there is no describe but just test or it in the file it will use exact match but not fullpath. (since there is none)

**Comment by firsttris** [comment]
and all special characters will be escaped of course.
