### ISSUE TITLE
Resolving to jest debug defaults to first folder in current workspace | automatically detect workspace subproject to find jest debug

### ISSUE THREAD

**Issue by Yimiprod** [firsttris/vscode-jest-runner#43]
Probably related to https://github.com/firsttris/vscode-jest-runner/issues/23

When using a workspace with multiple projects, the debug runner executes jest from the first folder in the current workspace if no explicit jest executable path had been configured, probably missing a call to `slash()` ?
https://github.com/firsttris/vscode-jest-runner/blob/b7839ea8c000b13b5b264b90ce8705da0c3adc47/src/extension.ts#L73

Is there any way to change that so it detects the correct workspace project that the file of the currently executed test resides in?

**Comment by firsttris** [comment]
hey @Yimiprod 
thx for your issue.

i think the issue could be this
https://github.com/firsttris/vscode-jest-runner/blob/b7839ea8c000b13b5b264b90ce8705da0c3adc47/src/extension.ts#L15

=> vscode.workspace.workspaceFolders[0]

i think we need some method to get the currentWorkspaceFolder or somehow get the index of the workspace your working in.

this feature you are using in vscode is called workspaces, right?

**Comment by Yimiprod** [comment]
Yes it's exactly this, i'm using workspaces. It's the featuer allowing to choose which folder i'm working on by projects.

**Comment by firsttris** [comment]
fixed it, will be included in version 0.4.3 release
