### ISSUE TITLE
Runs as VSCode project root, NOT working directory

### ISSUE THREAD

**Issue by samdoeswork** [firsttris/vscode-jest-runner#45]
Hi,
I have a setup with directories e.g.:
 /tests
 /func/func1

From func/func1 if I run "jest" in terminal the test runs fine, but when I run via. jest-runner it uses the project root scope, which means relative paths are broken (e.g. file loads).

I've tried the following:
- adding jest-config.json to the local folder
- adding jest config section to package.json in the local folder
- using VSCode settings variables in the jestrunner config path setting, e.g.: /${relativeFileDirname}/jest-config.json (they appear to be all blank at runtime)

Any advice on how to run as the open directory?

**Comment by firsttris** [comment]
hey @samdoeswork does this mean you are using workspaces within vscode?

there is already a issue

https://github.com/firsttris/vscode-jest-runner/issues/43

**Comment by firsttris** [comment]
fixed it, will be included in version 0.4.3 release
