### ISSUE TITLE
command 'extension.runJestFile' not found

### ISSUE THREAD

**Issue by andypearson** [firsttris/vscode-jest-runner#48]
First up, thanks for this amazing extension! My Jest workflow is so smooth with it.

It seems that all versions since `0.4.3` when I try and "Run Jest" or "Run Jest file" I get the following message:

```
command 'extension.runJestFile' not found
```

In the console I see the following error:

```
Activating extension 'firsttris.vscode-jest-runner' failed: Cannot find module 'escape-string-regexp'
Require stack:
- /Users/andypearson/.vscode/extensions/firsttris.vscode-jest-runner-0.4.5/out/jestRunner.js
- /Users/andypearson/.vscode/extensions/firsttris.vscode-jest-runner-0.4.5/out/extension.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js.
```

Rolling back to `0.4.2` fixes the problem and makes the commands work again.

Also, a small thing I noticed is that the recent entries in the change log are listed as happening in 2017, which confused me for a second :)

**Comment by andypearson** [comment]
A little more of a dig, I think that `"escape-string-regexp": "^2.0.0",` should be in `dependencies` instead of `devDependencies`, although I can't say that for sure as I don't know how VSCode extensions work with `package.json`.

Shall I try and figure that our and submit a PR?

**Comment by iosdev-republicofapps** [comment]
This just broke for me as well.  I can't seem to get it to run any more.  `runJest` is also broken.

Is there any workaround?

@andypearson did you find a workaround?

I really love this extension :-) and this is slowing down my workflow with it broken.  :-(

**Comment by iosdev-republicofapps** [comment]
OK, I rolled back to version 0.4.2 and it seems to be working again now.  See [How to Rollback a VSCode Extension Version](https://stackoverflow.com/a/53755378/961886) for details.

**Comment by aaronamm** [comment]
@andypearson @andypearson  you guys are the man. Thank you so much. After rollback, everything works as expected.

**Comment by firsttris** [comment]
thank for reporting that issue.
strange that my local build was working while the store build was not.
i fixed this issue in 0.4.7

can you please confirm that 0.4.7 is working for you?

**Comment by iosdev-republicofapps** [comment]
HI @firsttris , no version 0.4.7 is also broken, but differently.  I upgraded to 0.4.7 and it dies with "Found non-callable @@iterator" and Jest won't run and the extension doesn't seem to work.  Neither developer tools nor extension host logs show any errors.  Not sure what the problem is but 0.4.7 does not work.  Happy to help test other versions or attach logs if you give me some directions!  :-)

So I'm going to revert to 0.4.2 again.

**Comment by firsttris** [comment]
which OS are you using? 

which vscode version?

is there any output in there terminal at all?

**Comment by firsttris** [comment]
on my machine (manjaro & vscode 1.4.1) 
i can't reproduce your issue
![image](https://user-images.githubusercontent.com/1709260/70859220-58531880-1f10-11ea-9abf-99c38076a588.png)

maybe because some other vscode dependencies have also been updated?

**Comment by firsttris** [comment]
also tested on Windows10 with older vscode version
![image](https://user-images.githubusercontent.com/1709260/70859845-fbf4f680-1f19-11ea-9e5c-cd0a16c7be5d.png)

**Comment by iosdev-republicofapps** [comment]
macOS Mojave
  
latest vscode version   
  

  
I can get you the exact version numbers in the morning if that helps?
  

  
I tried turning off other extensions but that didn’t help.    It’s definitely vscode-jest-runner as far as I can tell.    Reverting to earlier versions of this extension makes the problem go away.
  

  
Any ideas?
  

  
  

  
  
>

**Comment by firsttris** [comment]
will do some testing in osx and report back

**Comment by iosdev-republicofapps** [comment]
Thanks!
  

  
  

  
  
>

**Comment by firsttris** [comment]
tested 0.4.7 on a macbook pro with darwin. 

seems to work well :man_shrugging: 

![image](https://user-images.githubusercontent.com/1709260/70864758-83ac2680-1f55-11ea-97be-8722ba077872.png)

maybe the issue is on your end?

i put some basic test example projects in the repository:
https://github.com/firsttris/vscode-jest-runner/tree/master/test/Projekt%20A

if you still think there is a issue in the version you could probably create a reproducible example.

**Comment by firsttris** [comment]
@iosdev-republicofapps remove your jestrunner config from you vscode settings.json, there was some changes. wrong config could create such issues. will check if can add some error handling.

**Comment by andypearson** [comment]
Sorry for the late reply, but `0.4.9` is working nicely for me again. Thanks for your hard work @firsttris!
