### ISSUE TITLE
Nested describes result in wrong jest command

### ISSUE THREAD

**Issue by matdurand** [firsttris/vscode-jest-runner#49]
Hi,

When a test is nested inside more than one describe, the resulting jest command include a "-t" using a starts with regex "^" but using the text from the describe closest to the test. This make jest skips all the tests because the regex doesnt match anything.

Here is an example:
```
describe('test1', () => {
  describe('test2', () => {
    it('should run this test', () => {
      expect(true).toBe(true);
    });
  });
});
```
and the resulting command has the following options
```
-t '^test2 should run this test$'
```

but it should be
```
-t '^test1 test2 should run this test$'
```

Great extension by the way!

**Comment by firsttris** [comment]
Thx for your issue. Did not thought about nested describe. I will fix this asap.

**Comment by firsttris** [comment]
please check version 0.4.9 where i cover the most complex test cases :)

if you find other issues please do not hesitate to report them

**Comment by heavenkiller2018** [comment]
i have the same trouble:Nested describes can't run! I hope it will be resolved as soon as possible!

**Comment by firsttris** [comment]
which version a you using? 0.4.15 is the recent one.

for me nested describes works well, see here:
![image](https://user-images.githubusercontent.com/1709260/73608769-1157da00-45c7-11ea-96dc-e0839aef53c6.png)
