### ISSUE TITLE
Undefined error starting test where cursor is

### ISSUE THREAD

**Issue by matdurand** [firsttris/vscode-jest-runner#50]
Following the #49 fix, I now get an error message "Cannot read property 'replace' of undefined" when I place my cursor inside a test and try to run. If I place my cursor in the test name (the string inside the it(...)), it works, but with the cursor on any line inside the test, I get the error.

My version is 0.4.9

**Comment by firsttris** [comment]
Yes, before we used different approach for parsing the test. We where traversing Up from the current line. now i took the test Parser from jest itself. i can now identify the Test with the Line Numbers. Which made alot stuff easier. Downside is when you do Not click in the exact Line i cant find the test.

**Comment by firsttris** [comment]
Ah but there is a Line range for each Test, maybe i can add this Feature back.

**Comment by firsttris** [comment]
fixed in 0.4.11, please verify

**Comment by matdurand** [comment]
Yes, fixed. Thanks
