### ISSUE TITLE
"Run Jest" and "Debug Jest" now do nothing if you don't select the line where the test start

### ISSUE THREAD

**Issue by edemartel** [firsttris/vscode-jest-runner#52]
Since the last update, the "Run Jest" and "Debug Jest" commands no longer do anything if the line your cursor is on isn't the one declaring the test.

Previously you could put your cursor at pretty much any location within the test function and it would work. This worked really well, and now it's a bit of a pain to use.

Is there anyway to revert to the previous behavior?

Thanks.

**Comment by firsttris** [comment]
yes we changed the test parser, the new parser identifies the test with the line number.

but i will bring that feature back shortly

**Comment by firsttris** [comment]
fixed in 0.4.11, please verify

**Comment by RandomEngy** [comment]
Verified that it works any line within a specific test now.
