### ISSUE TITLE
Right click -> Run Jest outside of a describe block does nothing

### ISSUE THREAD

**Issue by RandomEngy** [firsttris/vscode-jest-runner#54]
If you right click at the top of the file and choose "Run Jest", nothing happens. It should run all tests in the file.

Tested in 0.4.11

**Comment by firsttris** [comment]
I thought for this purpose would be the "Run Jest File" option?

**Comment by RandomEngy** [comment]
Yes, that does the right thing. But I think it makes sense that if you right click on the contents of a test file and click "Run Jest", it stands to reason that it would run the tests in that file. At the very least there should be some kind of message popup via vscode.window.showInformationMessage() or something to explain why it didn't work.

Nothing happening and no feedback makes it seem like it's broken.

**Comment by firsttris** [comment]
oh i didn't even know about this feature. will fix it soon. thx for your ticket.

**Comment by RandomEngy** [comment]
Thanks!

**Comment by viciteufel** [comment]
Fixed in version 0.4.18
