### ISSUE TITLE
Doesn't work with test.each

### ISSUE THREAD

**Issue by zyy7259** [firsttris/vscode-jest-runner#55]
Right clicking in the body of a [test.each](https://jestjs.io/docs/en/api#testeachtablename-fn-timeout) and selecting `Run Jest` doesn't trigger jest.

**Comment by firsttris** [comment]
hey @zyy7259, i did not consinder this case, will provide support with the next version.
thx for your issue.

**Comment by firsttris** [comment]
hey @zyy7259 

the issue is that with
jest-editor-support (https://github.com/jest-community/jest-editor-support)
the jest test parser for vscode addons its not possible to get the name of a test.each element.

BUT

if you highlight/select the name of the test and it will not use the parser instead what you actually have seleced.
(some kind of fallback logic)

![image](https://user-images.githubusercontent.com/1709260/72841530-db495a80-3c96-11ea-85d7-a0eed72d13c4.png)

**Comment by firsttris** [comment]
created an issue in jest-editor-support

**Comment by PizzaPartyInc** [comment]
Hi!
First, Thanks for the great Extension!

I wanted to add that even if related bugs are fixed, I'm having some doubts that it will be possible to fully fix this. The case which would probably not be possible to cover is when placeholders are used in the title of the test, e.g.
```ts
it.each([
    [1, 1, 2],
    [1, 2, 3],
    [2, 1, 3],
])('wtf %i %i %i', (a, b, expected) => {
    expect(a + b).toBe(expected);
});
```
This will print tests like:
`wtf 1 1 2`
`wtf 1 2 3`
`wtf 2 1 3`

And passing a parameter to jest CLI like `-t ''wtf %i %i %i''` will not work, while passing `-t "wtf 1 1 2"` will call a test only once and 2 other times will be skipped. 

Is such case something that can be worked around by anything except by highlighting just the 'wtf' part?

Highlighting just part of the test title without placeholder parts actually works fine =)

**Comment by firsttris** [comment]
@PizzaPartyInc thats absolutly correct. but we could probably achieve the something like "-t wtf" without the need of highlighting it, if this can be parsed by the jest parser of jest-editor-support. which means you can right click it.

this featue has now been implemented in jest-editor-support v28.0.0-beta.0 https://github.com/jest-community/jest-editor-support/releases/tag/v28.0.0-beta.0

**Comment by Cellule** [comment]
One thing to note is that if a test file contains a single `test.each` all the `Run|Debug` buttons disappear
![jest-runner-each](https://user-images.githubusercontent.com/4157103/92316859-a7be0500-efc7-11ea-88e7-ae8f02ef9f51.gif)

**Comment by Cellule** [comment]
> One thing to note is that if a test file contains a single `test.each` all the `Run|Debug` buttons disappear

I've confirmed that  `jest-editor-support v28.0.0-beta.0` fixes that issue, but it still has the problem where formatting elements remain in the test name 

```
$ node "…\jest\bin\jest.js" "…/__tests__/testfile.spec.ts" -t "test with .each: %s" --runInBand --forceExit
Test Suites: 1 skipped, 0 of 1 total
Tests:       7 skipped, 7 total
Snapshots:   0 total
Time:        6.352s, estimated 8s
```

**Comment by dcrystalj** [comment]
@Cellule can you try again? looks like this was addressed recently https://github.com/jest-community/jest-editor-support/pull/57

**Comment by Cellule** [comment]
Like I said last time, it is already mostly working with v28, however this extension needs to update to it because it's a major version it won't automatically update
That PR you linked might make additional fixes, but I haven't tried it out yet

**Comment by firsttris** [comment]
test.each is supported now

**Comment by Cellule** [comment]
Just tested it and it works perfectly ! Thanks

**Comment by PizzaPartyInc** [comment]
Yep! Works nicely! Thanks!
Found just one small issue. You cannot quote placeholders in test title. e.g. This works
```ts
it.each([1, 2, 3])('wrap something into quotes: %s', async (num) => {
   expect(num).toBe(num);
});
```

And this throws an error:
```
it.each([1, 2, 3])('wrap something into quotes: "%s"', async (num) => {
   expect(num).toBe(num);
});
```

```bash
PS C:\Project_Name> node "C:\Project_Name/node_modules/jest/bin/jest.js" "C:\Project_Name/test_file.spec.ts" -c "C:\Project_Name/jest.config.js" -t "wrap something into quotes: "(.*?)""
.*? : The term '.*?' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:337
+ ... wrap something into quotes: "(.*?)""
+                                                                    ~~~
    + CategoryInfo          : ObjectNotFound: (.*?:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
Not sure if having quoted placeholders is a good approach or not... =)
Also, maybe it's just a Windows thing...
