### ISSUE TITLE
Codelens option to start Tests

### ISSUE THREAD

**Issue by firsttris** [firsttris/vscode-jest-runner#56]
Abstract:
From my understanding a codelens option is a clickable link in your code, which could enable you to start jest in run or debug mode.

**Comment by wald-tq** [comment]
On the first look integrating code-lens looks quite complicated for me. But I have never touched the Visual Studio Code API.

https://code.visualstudio.com/blogs/2017/02/12/code-lens-roundup

https://code.visualstudio.com/api/language-extensions/programmatic-language-features#codelens-show-actionable-context-information-within-source-code

Some example: https://github.com/kisstkondoros/codemetrics

**Comment by firsttris** [comment]
Thx for your research. My understanding is we need to write some CodelensProvider Class which tells vscods when to display actionable content and what todo with it.
