### ISSUE TITLE
Run with coverage as a separate command

### ISSUE THREAD

**Issue by matdurand** [firsttris/vscode-jest-runner#58]
I know that we can specify the --coverage in the run options, but in my usual workflow, I write/run a bunch of tests one by one for a file, and when I'm done, I want to run the whole file with coverage to see if I missed something. So adding the --coverage in the options runs it every time, which slows things down so it's a no go.

If I had a "Run with coverage" command, I could set a separate keybinding for it and run it easily after I'm done with a test file. The workaround for now is to run the test for the whole file, and then edit the command in the terminal to add --coverage.

**Comment by firsttris** [comment]
hey @matdurand 
thx for your ticket.

i understood why you need this.

would it be okay if we add this to the command palette (Shift + String + P)?

we should avoid adding many items to the context menu because we cannot limit them to test files only.

**Comment by matdurand** [comment]
Yes, command palette is fine, that's exactly what I need. Thanks!

**Comment by viciteufel** [comment]
Available in version 0.4.18
