### ISSUE TITLE
individual test will not run if title contains comma

### ISSUE THREAD

**Issue by samthomson** [firsttris/vscode-jest-runner#60]
Selecting the test name `submits the form, via email verification, as expected` and right clicking > 'Run jest' silently fails. Nothing appears to happen.
If I remove the commas, making the test name `submits the form via email verification as expected` then it runs just that test as expected.

Version: 0.4.11
vscode: 1.41.1
os: popos/ubuntu 18

**Comment by samthomson** [comment]
Happy to try and help if you're open to PRs :slightly_smiling_face:

**Comment by firsttris** [comment]
Happy about any contributions. There are also some unit tests for the test Parser in src/Test/findfulltestname.test.ts Just add a Test with comma in test2.test.ts and extend FindFullTestName in src/Util. If all Tests a green your PR should be find.

**Comment by firsttris** [comment]
@samthomson 
please verify and report back if your issue is solved with 0.4.12 (removed this exact regex match feature)

if not - please provide test example & console output

**Comment by firsttris** [comment]
did some tests with 0.4.15

![image](https://user-images.githubusercontent.com/1709260/72839791-37aa7b00-3c93-11ea-87a1-8a6a9734d923.png)

feel free to re-open or create a new issue if you find one.

thx for reporting this issue
