### ISSUE TITLE
run previous test is just cd-ing when last run was debug

### ISSUE THREAD

**Issue by xenoterracide** [firsttris/vscode-jest-runner#63]
run previous test is just cd-ing when last run was debug, what I want for last run is to have it be able to do debug too, or maybe there should be a separate run with debug, but... that would be my more common use case.

**Comment by firsttris** [comment]
thx for reporting @xenoterracide 
will implement, once i find some free time.
regards
Tristan

**Comment by viciteufel** [comment]
Fixed with #71 
Available in version 0.4.16
