### ISSUE TITLE
How to specify the Node executable if I cannot modify the system environment?

### ISSUE THREAD

**Issue by zhangyanwei** [firsttris/vscode-jest-runner#64]
I cannot modify the system environment for security reason in our company, 
I tried to debug the Jest test cases in VSCode, but I got an error "Cannot find runtime 'node’ on PATH. Is ‘node’ installed?".

Can I specify the Node executable file through the settings.json for this VSCode extension?

**Comment by zhangyanwei** [comment]
After reading the source code, I know how to set it in settings.json file.
```json
"jestrunner.debugOptions": {
     "runtimeExecutable": ".../node-v10.16.3-win-x64/node.exe"
}
```

**Comment by KoltonG** [comment]
Thanks @zhangyanwei ! This worked for me 🎉
