### ISSUE TITLE
Attribute 'program' does not exist.

### ISSUE THREAD

**Issue by loisgomez** [firsttris/vscode-jest-runner#66]
Trying to debug a test pops the following alert on vs code. I have been using this feature before, somehow its broken now.

`Attribute 'program' does not exist.('/path/to/bin/jest')`

`Run jest` option works fine, `Debug jest` pops the above alert.

**Comment by firsttris** [comment]
hey @loisgomez 
i just tried to reproduce on my linux machine with:

VSCode Version: 1.44.2
Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
Date: 2020-04-16T17:50:03.709Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.5.16-1-MANJARO

![image](https://user-images.githubusercontent.com/1709260/80006685-83083b80-84c5-11ea-9591-a07804c1c07e.png)

was not able to reproduce your issue. 

where you abel to resolve you issue? or could you provide more information on your setup? (os,vscode version)
also do you have any jest-runner settings defined?

**Comment by loisgomez** [comment]
Thanks for your time reviewing this.
Turns out I had jest missconfigured somehow.
Will close this, since its no longer valid.
