### ISSUE TITLE
debug doesnt work with alternative jestcommand

### ISSUE THREAD

**Issue by hoeghen** [firsttris/vscode-jest-runner#67]
It seems that running in debug doesnt use the alternative jestCommand option.

**Comment by firsttris** [comment]
@hoeghen thx for reporting. that needs to be fixed!

**Comment by viciteufel** [comment]
In order to be able to debug tests VSCode has to know which executable to run - we link to the jest executable in the `node_modules` by default.

You can define a custom `jestPath` which will be used instead.
Can you check if this works for you?

**Comment by firsttris** [comment]
https://github.com/firsttris/vscode-jest-runner/blob/master/src/jestRunner.ts#L105
Debug uses alternativ jestPath instead of alternativ JestCommand.

JestCommand (like npm run test) is not possible for RunDebug
