### ISSUE TITLE
In jestrunner.jestPath, ${workspaceFolder} it is not replaced

### ISSUE THREAD

**Issue by gorka-gil-ob** [firsttris/vscode-jest-runner#69]
With this line in project settings:
"jestrunner.jestPath": "${workspaceFolder:projectA}/node_modules/jest/bin/jest.js"

Gives this error:
Error: Cannot find module "/path_to_project/${workspaceFolder:projectA}/node_modules/jest/bin/jest.js"

Looks like it is failing to replace ${workspaceFolder:projectA} (for multi root environments) with its value.
Also fail to replace normal variable ${workspaceFolder}.

This fails in Run and Run File, but both things works in Debug.

Using version: 0.4.15

**Comment by firsttris** [comment]
Hey @gorka-gil-ob 

there is no logic implemented that would replace ${workspaceFolder:projectA} with the correct path.

but its actually a very good idea, it would solve https://github.com/firsttris/vscode-jest-runner/issues/68

i will report back soon.

regards
Tristan

**Comment by jakedowns** [comment]
+1 for wanting to see this; i tried symlinking node_modules as a quick workaround, but that still broke. :/

**Comment by firsttris** [comment]
in version 0.4.24 you can define a fixed project path from where jest & config is used.

please re-open if this does not solve your issue.
