### ISSUE TITLE
Error: Cannot find module 'my_path\node_modulesjestbinjest.js'

### ISSUE THREAD

**Issue by chanakaHetti** [firsttris/vscode-jest-runner#7]
I just installed vscode-jest-runner and tried to run test. I got error like below.

Error: Cannot find module 'my_path\node_modulesjestbinjest.js'

**Comment by firsttris** [comment]
Hey.

may i asked on which OS you are?

i have just tested with vscode 1.25.1 on windows 10

for me it seems to working in Linux and also Windows 10

output of running a test:

PS D:\projects\timetracking-app> node d:\projects\timetracking-app\node_modules\jest\bin\jest.js -t "getHoursByDate"
 PASS  packages\server\src\collections\ComplainCollection.test.ts

Test Suites: 33 skipped, 1 passed, 1 of 34 total
Tests:       190 skipped, 1 passed, 191 total
Snapshots:   0 total
Time:        7.235s
Ran all test suites with tests matching "getHoursByDate".
PS D:\projects\timetracking-app>

regards
Tristan

**Comment by firsttris** [comment]
if you still experience such issues please reopen your issue
