### ISSUE TITLE
On code context menu "Debug Jest" not working (MacOS)

### ISSUE THREAD

**Issue by solarseven** [firsttris/vscode-jest-runner#75]
The "Run Jest" option in the context menu from right clicking on a code line inside *.test.js files does nothing.
However the "Run Jest File" context option works as expected.

Ran on MacOS Mojave 10.14.6

**Comment by solarseven** [comment]
This was not a was not a bug.
Just unclear that this is how you run Jest Runner on a specific line.

Solution: select the whole line to be tested, right click selection, select Debug Jest.

**Comment by firsttris** [comment]
hey @solarseven 

it should also be possible to just right-click somewhere inside a test or in the testname. selecting the whole text is more or less the fallback method.
