### ISSUE TITLE
disableOptimisticBPs flag

### ISSUE THREAD

**Issue by kirstyannepollock** [firsttris/vscode-jest-runner#85]
This is used normally in launch.json for debug launches to stop crazy breakpoint behaviour, like not stopping on breakpoints while debugging, breakpoints vanishing and (maybe) "phantom" break points that continually reappear sometimes a long time after being deleted.

How can I make sure JestRunner also uses this flag? Because I am wasting SO much time because of vanishing, moving and resurrecting breakpoints!

**Comment by firsttris** [comment]
hey @kirstyannepollock 

have you seen the notes in the README?

https://github.com/firsttris/vscode-jest-runner#notes-from-contributors

i think there is described what you want to achieve.

**Comment by kirstyannepollock** [comment]
@firsttris No! How did I miss that? Thanks
