### ISSUE TITLE
Run | Debug links disappear with concatenated test name strings.

### ISSUE THREAD

**Issue by coreyleelarson** [firsttris/vscode-jest-runner#87]
First off, great extension! However, the "Run | Debug" links disappear from the UI when an `it` or `describe` block name contains a concatenated string. I've included basic examples below:

**Working:**
```
describe('my test suite', () => {
  it('should do something', () => {
    expect(false).toBe(false);
  });
});
```

**Not Working (concatenation on same line):**
```
describe('my test suite', () => {
  it('should do ' + 'something', () => {
      expect(false).toBe(false);
    });
});
```

**Also Not Working (concatenation on different line):**
```
describe('my test suite', () => {
  it('should do '
    + 'something', () => {
      expect(false).toBe(false);
    });
});
```

FYI, I am using Jest Runner v0.4.22 and VSCode v1.46.1 on Windows 10

Let me know if you need any additional information. Thanks!

**Comment by moltar** [comment]
I think the general issue here is that no JS gets eval'ed to obtain the name. Using variables in test names also is not possible.

E.g. the following will fail:

```
describe(`${MyClass.name}`, () => {
  it('should work', () => {
    // ...
  })
})
```

The test runs as:

```
-t '\$\{MyClass\.name\} should work'
```

---

I am going to assume that loops probably also do not work.

**Comment by firsttris** [comment]
we have to find out if the jest parser of jest-editor-support is capable of evaluating there kinds of dynamic test names.

here you find the implementation of parser & codeLensProvider
https://github.com/firsttris/vscode-jest-runner/blob/master/src/JestRunnerCodeLensProvider.ts#L1

**Comment by coreyleelarson** [comment]
It looks like jest-editor-support currently only supports TemplateLiteral or CallExpression types:

https://github.com/jest-community/jest-editor-support/blob/master/src/parsers/babel_parser.js
```javascript
if (!name) {
  switch (arg.type) {
    case 'TemplateLiteral':
      name = _data.substring(arg.start + 1, arg.end - 1);
      break;
    case 'CallExpression':
      // a dynamic function: use a placeholder
      name = '__function__';
      break;
    default:
      throw new TypeError(`failed to update namedBlock from: ${JSON.stringify(bNode)}`);
  }
}
```
My original example parses as a BinaryExpression, so there would probably need to be some sort of mechanism to resolve the test name string from it in the format which jest expects.

Not sure if something like this exists or if it would need to be written. My experience with ASTs is minimal.

**Comment by firsttris** [comment]
![image](https://user-images.githubusercontent.com/1709260/120699782-21c8df00-c4b1-11eb-98ff-cbaf48a09c84.png)

jest-editor-support parser returns unsupported now

**Comment by coreyleelarson** [comment]
> ![image](https://user-images.githubusercontent.com/1709260/120699782-21c8df00-c4b1-11eb-98ff-cbaf48a09c84.png)
> 
> jest-editor-support parser returns unsupported now

I guess if it's unsupported then it's unsupported. 🤷‍♂️
