### ISSUE TITLE
[CRA] Not using "jestrunner.jestCommand" when running debug tests

### ISSUE THREAD

**Issue by davidlukerice** [firsttris/vscode-jest-runner#88]
In a `create-react-app` project, when running debug tests I'm running into syntax errors that seem to be caused by CRA not exposing a `jest-config`. 
It looks like a similar issue to https://github.com/firsttris/vscode-jest-runner/issues/20 but for the debug case.
With the following `settings.json`:
```
{
  "jestrunner.debugOptions": {
    "args": [
      "--no-cache",
      "--env=jest-environment-jsdom-sixteen",
      "--watchAll=false"
    ],
    "env": {
      "TZ": "America/Chicago"
    },
    "sourcemaps": "inline",
    "disableOptimisticBPs": true
  },
  "jestrunner.jestCommand": "npm run test -- --watchAll=false"
}
```
running tests work fine. It's just when I try to use "Debug Jest" option, it's throwing errors.

The resulting terminal (with `[...]` pieces pulled):
```
bash-3.2$  cd [repo folder] ; env TZ=America/Chicago /Users/davidrice/.nvm/versions/node/v12.16.3/bin/node --inspect-brk=35094 node_modules/.bin/jest --no-cache --env=jest-environment-jsdom-sixteen --watchAll=false [absolute path to test file] -t "[test name]" --runInBand 
Debugger listening on ws://127.0.0.1:35094/e530388c-8591-4657-ae28-ad93bbea0c3a
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
 FAIL  [test folder name]
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    [path to component]/styles.scss:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){.loading-overlay {
                                                                                             ^

    SyntaxError: Unexpected token '.'

      1 | import React from 'react';
      2 | import PropTypes from 'prop-types';
    > 3 | import './styles.scss';
        | ^
      4 | import Spinner from '../Spinner';
      5 | 
      6 | const LoadingOverlay = ({ inlineDisplay, opaque }) => (

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (src/components/LoadingOverlay/index.js:3:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        4.342s
Ran all test suites matching /\[test file path]/i with tests matching "[test file name]".
Waiting for the debugger to disconnect...
```

I can force it over to use react-scripts instead of jest with something like
```
  "jestrunner.debugOptions": {
    "program": "${workspaceRoot}/node_modules/.bin/react-scripts",
    "args": [
      "test",
      "--runInBand",
      "--no-cache",
      "--env=jest-environment-jsdom-sixteen",
      "--watchAll=false"
    ],
    "env": {
      "TZ": "America/Chicago"
    },
    "disableOptimisticBPs": true
  },
```
but I'm not sure how to get vscode debugging to connect to it correctly.

**Comment by firsttris** [comment]
hey @davidlukerice i can reproduce your issue, since im working currently working in a project where they also using CRA.

looking at the code

This is where the Debug config is created:
https://github.com/firsttris/vscode-jest-runner/blob/master/src/jestRunner.ts#L101

it uses a config settings for the executable:
https://github.com/firsttris/vscode-jest-runner/blob/master/src/jestRunnerConfig.ts#L23

try to set 'jestrunner.jestPath' to react-scripts.

would be nice if you could report back if that solves the issue, then i could add this information to the readme

**Comment by davidlukerice** [comment]
So a `settings.json` like this?
```
{
  "jestrunner.debugOptions": {
    "args": [
      "test",
      "--runInBand",
      "--no-cache",
      "--env=jest-environment-jsdom-sixteen",
      "--watchAll=false"
    ],
    "env": {
      "TZ": "America/Chicago"
    },
    "disableOptimisticBPs": true
  },
  "jestrunner.jestCommand": "npm run test -- --watchAll=false",
  "jestrunner.jestPath": "${workspaceRoot}/node_modules/.bin/react-scripts"
}
```
When I run "Debug" with that config, it'll run the test but doesn't stop on any breakpoints or `debugger;` statements I've put in.

Log:
```
bash-3.2$  env TZ=America/Chicago /Users/davidrice/.nvm/versions/node/v12.16.3/bin/node --inspect-brk=27881 node_modules/.bin/react-scripts test --runInBand --no-cache --env=jest-environment-jsdom-sixteen --watchAll=false [test file path]/index.test.js -t "[test name]" --runInBand 
Debugger listening on ws://127.0.0.1:27881/93e66212-6e56-44ae-88af-dde63875d25a
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.

 PASS  [test file path]/index.test.js (9.637s)
  [Test describe() name]
    ✓ [test name] (288ms)
    ○ skipped [other tests]
    ...

Test Suites: 1 passed, 1 total
Tests:       38 skipped, 1 passed, 39 total
Snapshots:   0 total
Time:        10.183s
Ran all test suites matching /\/[test file path]\/index.test.js/i with tests matching "[test file name]".
Waiting for the debugger to disconnect...
Killed: 9
```

**Comment by firsttris** [comment]
i need to investigate this issue

this settings are the settings for react-scripts:
https://create-react-app.dev/docs/debugging-tests/#debugging-tests-in-visual-studio-code

if this works the vanilla way, the issue has to be in my code-base

**Comment by Joseph-Brighton** [comment]
I have a similar problem with this as well, except when I set 'jestrunner.jestPath' to "${workspaceRoot}/node_modules/.bin/react-scripts", I instead get the issue where it says "Cannot launch prograim '{myRoute}/node_modules/.bin/react-scripts' ". I tried npm install to no effect.

**Comment by joequery** [comment]
I'm running into this as well. Same error as OP with `Jest encountered an unexpected token` when running Debug for a test

**Comment by firsttris** [comment]
I added the nessecary steps to the readme.md

1.) https://github.com/firsttris/vscode-jest-runner#usage-with-cra-or-similar-abstractions
2.) https://github.com/firsttris/vscode-jest-runner#debugging-jsxtsx-with-cra

re-open a new issue if it still doesn't work for you

**Comment by gurupras** [comment]
This is a bit tangential, but I think this wont work for VueJS.

Vue requires the following command-line: `vue-cli-service test:unit`.
Even if we could change `jestrunner.jestCommand` to be `./node_modules/.bin/vue-cli-service`, currently there is no way to ensure that `test:unit` gets passed in next. At least, I couldn't figure out how to do it.

**Comment by firsttris** [comment]
have you tried something like this ?

```
{
  "scripts": {
    "test-unit": "vue-cli-service test:unit",
  }
}
```

add `npm run test:unit --` as `jestrunner.jestCommand`

**Comment by gurupras** [comment]
I have. I meant specifically for debugging. Sorry, maybe this is the wrong issue to comment on.

**Comment by wakeGISer** [comment]
same issue with it
debugger mode can't get the `jestrunner.jestCommand` 
For example, i want to add next arguments after node excutable, but the debugger mode can't consume the jestCommand

**Comment by wakeGISer** [comment]
![image](https://user-images.githubusercontent.com/18297853/183254623-41fe6171-502a-427b-9ed0-84ddd401a38f.png)

**Comment by paulatay-abley** [comment]
this debug config override works for me. haven't have time to figure out the options sadly

```
 "jestrunner.debugOptions": {
    "program": "",
    "env": { "CI": "true" },
    "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/react-scripts",
    "args": ["test", "--runInBand", "--no-cache"],
    "cwd": "${workspaceRoot}",
    "protocol": "inspector",
    "console": "integratedTerminal",
    "internalConsoleOptions": "neverOpen"
  },
```

**Comment by jokerosky** [comment]
the way with _jestrunner.debugOptions_ works ↑

if you have a project created with CRA and then customized somehow, for me it was .tsconfig file, which I modified in order to have absolute imports from my project (_import { whatever } from'myproject/module'_ ) addition of **babel.config.js** and **jest.config.js** would not solve the problem, because we need to provide all custom configuration to jest, so it is reasonable to use the same _jestCommand_ both for Run and Debug options in VS Code editor.

**Comment by tahonaPL** [comment]
I will drop my case here. In code package.json I'm using     "type": "module" . So to use jest I need to use experimental-vm-modules flag. 
    
    "jestrunner.jestCommand": "export NODE_OPTIONS=--experimental-vm-modules && jest",
    "jestrunner.debugOptions": {
        "env": { "NODE_OPTIONS": "--experimental-vm-modules" },
    }

**Comment by PhilippeRoy** [comment]
Hope this helps some, I got debug to work for CRA in vscode by doing the following: https://github.com/firsttris/vscode-jest-runner/issues/315
