### ISSUE TITLE
WSL2 - Support running / debugging tests on mapped network drives

### ISSUE THREAD

**Issue by EyalPerry** [firsttris/vscode-jest-runner#90]
**Description**
When running / debugging a test via code lens / context menu, I am getting the following error for tests located in a WSL2 folder:
![error](https://user-images.githubusercontent.com/9663481/87834103-38af1480-c892-11ea-9381-11c7387e0356.png)
(Z is the network drive to which I mapped the WSL2 root folder)
Note that the file is matched according to the output, but the test itself is not run.

jest.config.js
```javascript
const { pathsToModuleNameMapper } = require("ts-jest/utils");
const { compilerOptions } = require("./tsconfig");

module.exports = {
   moduleNameMapper: pathsToModuleNameMapper(compilerOptions.paths, { prefix: "<rootDir>/" }),
};
```
jest version: 26.0.4
The test runs just fine in WSL2:
![success](https://user-images.githubusercontent.com/9663481/87834304-c12db500-c892-11ea-85fb-25622c10d512.png)
The test also runs just fine if I open vscode via the Remote- WSL extension.
It's just the network path it's failing with.

**Comment by firsttris** [comment]
unfortunatley i don't think i can help you with this issue, or if its even related to my extension code.

thats why im closing.

please re-open a new ticket if you still need support.
