### ISSUE TITLE
Most recent vscode update broke the debugging feature of this extension

### ISSUE THREAD

**Issue by jim-moody** [firsttris/vscode-jest-runner#94]
Seems that the June VSCode update broke debugging, more info to follow.

**Comment by Livven** [comment]
Just as an additional data point, debugging is working on 1.47.3 for me.

**Comment by jim-moody** [comment]
Ok I pulled together more information. I created a small repo that reproduces the issue:
https://github.com/jim-moody/vscode-jest-debug-issue

And I recorded two videos.

Video 1 - VSCode v1.47 - The debugger skips the breakpoint within the `sum` function
![1 47](https://user-images.githubusercontent.com/26190589/90029572-03c39100-dc89-11ea-871b-913fc63ac63b.gif)

Video 2 - VSCode v1.46 - The debugger properly stops at the breakpoint within the `sum` function
![1 46](https://user-images.githubusercontent.com/26190589/90029445-e2fb3b80-dc88-11ea-99d5-4bdf3a0fae97.gif)

**Comment by jim-moody** [comment]
Seems that its fixed in 1.48, so the root cause must have been an issue with VSCode
