### ISSUE TITLE
Not able to run Jest Runner using CRA

### ISSUE THREAD

**Issue by Joseph-Brighton** [firsttris/vscode-jest-runner#95]
Hi,

I might be just doing something wrong but can you point me to a sample configuration of this extension working with CRA? for me its not working at all, it keeps trying to use standard jest commands rather than npm run test.

Thanks,
Joseph

**Comment by firsttris** [comment]
currently it only works for the "Run Jest" command not for "Debug Jest".

For CRA put this in your settings.json:

"jestrunner.jestCommand": "npm run test --",

please re-open if your issue persists

regards
Tristan

**Comment by PhilippeRoy** [comment]
Hope this helps some, I got debug to work for CRA in vscode by doing the following: https://github.com/firsttris/vscode-jest-runner/issues/315
