### ISSUE TITLE
Optional dynamic lookup of jest.config.js being used by the jest command

### ISSUE THREAD

**Issue by PBug90** [firsttris/vscode-jest-runner#96]
Assume you have the following directory layout:

> /package.json
> /test/integration/integration1.test.js
> /test/integration/jest.config.js
> 
> /test/unit/test1.test.js
> /test/unit/jest.config.js
> 

If I am not mistaken, I can currently not utilize the test-type specific jest config files with this plugin. It would be neat to support this out of the box, so if I execute a specific test in _integration1.test.js_, jest uses the next available jest.config.js file, in the example above _/test/integration/jest.config.js_.

https://github.com/facebook/jest/issues/5921 is basically the same issue and still open. Maybe the mentioned npm package could be used here aswell.

This keeps the jest configuration in scope with the test types and would provide a consistent api for our developers according to the way our CI scripts are setup.

**Comment by firsttris** [comment]
in verion 0.4.24 you can define a fixed project path from where jest is used.

**Comment by PBug90** [comment]
I dont think that this will solve my issue. I basically want the UI-triggered test to use the next available jest.config.js in the same or a parent folder.

**Comment by firsttris** [comment]
exacly thats why i didn't close this issue.

**Comment by PBug90** [comment]
Are you interested in a PR? I could take a look at it and implement it myself.

**Comment by firsttris** [comment]
@PBug90 yes, that would be awesome!

**Comment by firsttris** [comment]
Dynamic Jest config (jest.config.js) resolution is now available in version 0.4.27 thx to @vrptnc 

please test & report back
