### ISSUE TITLE
Ability to not focus terminal window

### ISSUE THREAD

**Issue by advzr** [firsttris/vscode-jest-runner#97]
Now if you run a test a terminal window appears with jest cli running. That terminal window catches focus. It would be more convenient to keep the editor window focused especially for vscodevim users. I'd like to start a test and be able to continue navigate the code in the editor. But now I have to switch focus to the editor window manually.

**Comment by akowalz** [comment]
I opened a PR for this functionality, please give it a review! 

https://github.com/firsttris/vscode-jest-runner/pull/205
