### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by aykutkilic** [firsttris/vscode-jest-runner#99]
When I click Debug link on top of the test the generated command is:
`cmd /C "set "NODE_OPTIONS=--require "c:/Users/u22o91/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/ms-vscode.js-debug/src/bootloader.bundle.js" " && set "VSCODE_INSPECTOR_OPTIONS={"inspectorIpc":"\\\\.\\pipe\\node-cdp.8788-3.sock","deferredMode":false,"waitForDebugger":"","execPath":"C:\\devtools\\nodejs\\12.6.0\\node.exe","onlyEntrypoint":false,"fileCallback":"C:\\Temp\\node-debug-callback-e246da0a5dce7eae"}" && C:\devtools\nodejs\12.6.0\node.exe .\node_modules\jest\bin\jest.js c:/git/start-rtl/src/TodoList.test.js -t "<App /> Renders <TodoList /> component" --runInBand "`
And the result is:
The system cannot find the file specified.

Is this command line correct? Quotes seem to be nested.

**Comment by firsttris** [comment]
can you provide more details? 
which os?
vscode version?
which terminal are you using?

please note: some weeks ago there was some vscode issue with debugging

regards
Tristan

**Comment by firsttris** [comment]
Please re-open if you still have issues.

regards
Tristan

**Comment by aykutkilic** [comment]
It is fixed! Now things seem working. Thanks.
